TOPDIR = ../../../..
LOCALDIR = imc/lecturnity/util/wizards

CLASSES = WizardPanel.class Wizard.class WizardData.class \
	WizardButton.class ButtonPanel.class WizardListener.class \
	WizardEvent.class WizardTextArea.class

include ../Makefile.inc
