Attribute VB_Name = "DlgStrings"
Option Explicit

'Declare Function GetProgramLanguage Lib "e:\ppt2epx\ppt_dll.dll" () As Integer
Public Const MAXLANGID As Long = 2

Enum ResStrings
    ERR_NO_OPENED_PRES = 2
    ERR_LEC_NOT_INSTALLED = 3
    
    ERR_CANNOT_OPEN_LSD = 10
    ERR_DISK_FULL = 20
    ERR_NOPAGE = 30
    ERR_WRONG_FILENAME = 40
    ERR_WRONG_PRESENTATIONNAME = 41
    ERR_OVERWRITE_IMAGE = 50
    ERR_OVERWRITE_FILE1 = 51
    ERR_OVERWRITE_FILE2 = 52
    ERR_DIRECTORY_ERROR = 53
    
    CMD_PREV = 101
    CMD_NEXT = 102
    CMD_CANCEL = 103
    CMD_FINISH = 104
    CMD_QUIT = 105
    CMD_OPEN = 106
    CMD_BROWSE = 107
    
    HEADER_START = 111
    SUBHEADER_START = 112
    SELECTION_DESCRIPTION = 113
    SELECTION_ERROR = 114
    STR_ALLSLIDES = 115
    STR_CURSLIDE = 116
    STR_SELSLIDES = 117
    
    HEADER_FILE = 121
    SUBHEADER_FILE = 122
    TXT_BROWSE_CAPTION = 123
    
    HEADER_PROGRESS = 131
    SUBHEADER_PROGRESS = 132
    TXT_IMPORT_TEMPLATE = 133
    TXT_IMPORT_SLIDE = 134
    TXT_TIME_LEFT = 136
    TXT_DURATION = 137
    
    HEADER_SUMMARY = 141
    SUBHEADER_SUMMARY = 142
    TXT_CONVERSION_FINISHED = 143
    OBJECT_WARNING_MESSAGE = 144
    SHOW_DETAILS = 145
    HIDE_DETAILS = 146
    GRID_CAPTION_PAGE = 147
    GRID_CAPTION_OBJECT = 148
    GRID_CAPTION_COUNT = 149
    GRID_CAPTION_DESCRIPTION = 150
    SHOW_NEVER_AGAIN_MESSAGE = 160

    STR_CONFIRM_SAVE = 171
    CMD_YES = 173
    CMD_NO = 174
    
    NO_LECTURNITY_HOME = 301
    NO_VALID_LECTURNITY_HOME = 302
    BROWSE_DIRECTORY = 303

    EXT_SAVEAS = 501
    EXT_LSD_DESC = 505
    EXT_ALL_FILE_DESC = 506
    
    SOURCE_DOCUMENT = 600
    RECORDINGS = 601
    CD_PROJECTS = 602

    MNU_SAVEASLSD = 901
    MNU_OPENINASSISTANT = 902
    
    DLG_CAPTION = 999
End Enum

Enum ResPictures
    PIC_LOGOLEFT = 101
    PIC_LOGORIGHT = 102
End Enum

Enum ErrCodes
    ErrBeginPage = 101
    ErrEndPage = 102
End Enum


