//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by audioresources.rc
//
#define AUDIO_NOMEM                     1
#define IDS_PREP_FULLSCREEN             2
#define AUDIO_IOERR                     3
#define IDS_PREP_CUSTOM                 4
#define AUDIO_HEADER                    5
#define IDS_PREP_WIDTH                  6
#define AUDIO_INIT_ERR                  7
#define IDS_PREP_HEIGHT                 8
#define AUDIO_FORMAT_ERR                9
#define IDS_PREP_START_SEL              10
#define AUDIO_NODEVICE                  11
#define IDS_PREP_START_REC              12
#define AUDIO_GETCAPS_ERR               13
#define IDS_PREP_REC_SETTINGS           14
#define VIDEO_NOWINDOW                  15
#define IDS_PREP_AUDIO_SETTINGS         16
#define VIDEO_NOCAPWIN                  17
#define IDS_PREP_REC_AUDIO              18
#define VIDEO_NOMEM_BITMAP              19
#define IDC_CURSOR_POLYLINE             19
#define IDC_CURSOR_RECTANGLE            20
#define IDS_PREP_SHOW_HIDE              20
#define VIDEO_NOFILENAME                21
#define IDC_CURSOR_OVAL                 21
#define IDC_CURSOR_POLYGON              22
#define IDS_PREP_SHORTCUT               22
#define VIDEO_NOMEM_HEADER              23
#define IDC_CURSOR_TEXT                 23
#define IDC_CURSOR_LINE                 24
#define IDS_PREP_CTRL                   24
#define VIDEO_CODEC_INITERR             25
#define IDC_CURSOR_FREEHAND             25
#define IDS_WAIT_FOR_CLICKS             26
#define VIDEO_CODEC_BADFORMAT           27
#define VIDEO_CODEC_BEGINERR            29
#define RIFF_NOBUFWRITE                 31
#define RIFF_OPENCHUNKERR               34
#define RIFF_CLOSECHUNKERR              36
#define RIFF_CLOSECHUNKERR2             38
#define RIFF_WRITEERR                   40
#define VIDEO_IO_NOWRITE                42
#define VIDEO_NOMEM_INDEX               44
#define RIFF_CLOSEERR                   46
#define VIDEO_INDEX_WRITEERR            48
#define VIDEO_HDR_UPDATEERR             50
#define VIDEO_NOEVENTS                  52
#define VIDEO_INIT_ERROR                54
#define VIDEO_INIT_TIMEOUT              56
#define VIDEO_NOMEM_DRIVER              58
#define VIDEO_NOTTWICE                  60
#define VIDEO_RGB_CODECNAME             62
#define VIDEO_RGB_CODECDESC             64
#define AV_NOAUDIO                      66
#define AV_IN_PROGRESS                  68
#define AV_NOT_PAUSED                   70
#define AV_NOVIDEO                      72
#define VIDEO_DEV_ERROR                 74
#define VIDEO_DEV_NOCONNECT             76
#define VIDEO_DEV_NOCAPS                78
#define VIDEO_DEV_NOSETTINGS            80
#define VIDEO_DEV_NOSETSETTINGS         82
#define VIDEO_NO_RECOMPRESSDESC         84
#define VIDEO_NO_RECOMPRESS             86
#define AUDIO_NOTHREAD                  88
#define AUDIO_OUTPUT_ERROR              90
#define RIFF_ERROR_OUTPUT               92
#define VIDEO_START_FAILED              94
#define VIDEO_CAP_ERROR                 96
#define MIXER_SETSOURCE_FAILED          98
#define MIXER_SETVOLUME_FAILED          100
#define MSGBOX_WARNING                  102
#define VIDEO_CODEC_UNSUPPORTED         104
#define IDI_RCLICK                      104
#define IDI_CLICK                       105
#define VIDEO_CODEC_MEMORY              106
#define IDC_TELEPOINTER                 106
#define VIDEO_CODEC_INTERNAL            108
#define IDD_DV_DECODER                  108
#define VIDEO_CODEC_BADFLAGS            110
#define IDC_CURSOR_SG_SELECTION         111
#define VIDEO_CODEC_BADPARAM            112
#define IDR_PNG1                        113
#define VIDEO_CODEC_BADSIZE             114
#define VIDEO_CODEC_BADHANDLE           116
#define IDR_CLOSE_SGHINTS               117
#define VIDEO_CODEC_CANTUPDATE          118
#define IDR_CUSTOM_AREA                 118
#define IDR_FULL_SCREEN                 119
#define VIDEO_CODEC_ABORT               120
#define IDR_RECORD                      120
#define IDR_SG_DRAW_CONTEXT             121
#define VIDEO_CODEC_ERROR               122
#define VIDEO_CODEC_BADBITDEPTH         124
#define VIDEO_CODEC_BADIMAGESIZE        126
#define VIDEO_CODEC_UNKNOWN             128
#define VIDEO_FORMAT_SIZE               130
#define VIDEO_START_FAILED2             132
#define ANNO_DELETEALL                  134
#define AUDIO_CLICK_TOO_LONG            136
#define AUDIO_NO_CLICK_NOISE            138
#define DVDEC_CONVERT                   140
#define DVDEC_RESOLUTION                142
#define DVDEC_FULL                      144
#define DVDEC_HALF                      146
#define DVDEC_QUARTER                   148
#define DVDEC_DC                        150
#define DVDEC_DC_en                     151
#define CAPTION_OK                      152
#define CAPTION_CANCEL                  154
#define WDM_ID_CAPTUREFILTER            156
#define WDM_ID_ANALOGVIDEODECODER       158
#define WDM_ID_STREAMCONFIG             160
#define WDM_ID_CROSSBAR                 162
#define WDM_ID_TVTUNER                  164
#define WDM_ID_DV_DECODER               166
#define WDM_ID_VFW_SOURCE               168
#define WDM_ID_VFW_FORMAT               170
#define WDM_ID_VFW_DISPLAY              172
#define WDM_ID_UNKNOWN                  174
#define WDM_ERR_DEVICES                 176
#define WDM_VFW_EXISTS                  178
#define WDM_ERR_INIT                    180
#define WDM_ERR_START                   182
#define WDM_ERR_NODEVICE                184
#define WEM_ERR_NODEVICE                185
#define SG_NOSTART_WHILE_PAUSED         187
#define IDC_CURSOR_TELEPOINTER_INACTIVE 188
#define IDC_CURSOR_MARKER_BLUE          189
#define IDC_CURSOR_MARKER_GREEN         190
#define IDC_CURSOR_MARKER_MAGENTA       192
#define IDC_CURSOR_MARKER_ORANGE        193
#define IDC_CURSOR_MARKER_RED           194
#define IDC_CURSOR_MARKER_YELLOW        195
#define IDC_CURSOR_PEN_BLACK            196
#define IDC_CURSOR_PEN_BLUE             197
#define IDC_CURSOR_PEN_CYAN             198
#define IDC_CURSOR_PEN_GREEN            199
#define IDC_CURSOR_PEN_MAGENTA          200
#define IDC_CURSOR_PEN_RED              201
#define IDC_CURSOR_PEN_WHITE            202
#define IDC_CURSOR_PEN_YELLOW           203
#define IDC_DV_CONVERT                  1000
#define IDC_DV_FULL                     1001
#define IDC_DV_HALF                     1002
#define IDC_DV_QUARTER                  1003
#define IDC_DV_STAMP                    1004
#define IDC_DV_RESOLUTION               1005
#define IDC_EDIT_X                      1010
#define IDC_EDIT_Y                      1012
#define IDC_EDIT_WIDTH                  1013
#define IDC_EDIT_HEIGHT                 1014
#define IDC_SPIN_X                      1015
#define IDC_SPIN_Y                      1016
#define IDC_SPIN_WIDTH                  1017
#define IDC_SPIN_HEIGHT                 1018
#define IDC_RECORDFULLSCREEN            1019
#define IDC_RECORDCUSTOM                1020
#define IDC_STARTSELECTION              1021
#define IDC_STARTRECORDING              1022
#define IDC_SHOWAUDIOSETTINGS           1023
#define IDC_SHOWPRESENTATIONBAR         1024
#define IDC_SHOWSGSETTINGS              1025
#define IDC_AUDIO_SLIDER                1026
#define IDC_VIEW_AUDIO                  1027
#define IDC_CHECK_START_CTRL            1028
#define IDC_CHECK_START_ALT             1029
#define IDC_CHECK_START_SHIFT           1030
#define IDC_COMBO_START                 1031
#define IDC_CHECK_REDUCE_CTRL           1032
#define IDC_CHECK_REDUCE_ALT            1033
#define IDC_CHECK_REDUCE_SHIFT          1034
#define IDC_COMBO_REDUCE                1035
#define IDC_CHECK_MINIMIZE_CTRL         1036
#define IDC_CHECK_MINIMIZE_ALT          1037
#define IDC_CHECK_MINIMIZE_SHIFT        1038
#define IDC_COMBO_MINIMIZE              1039
#define IDC_CANCELSELECTION             1040
#define IDB_PREPARATION_BAR_BKG         1041
#define IDC_RECORDAUDIO                 1042
#define IDC_DELETE_ALL                  1043

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        204
#define _APS_NEXT_COMMAND_VALUE         40002
#define _APS_NEXT_CONTROL_VALUE         1044
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
