# Makefile 24.6.00 

TOPDIR = ../../../..
LOCALDIR = imc/epresenter/player/util

CLASSES = TimeFormat.class TimeSource.class \
          XmlTag.class Timeable.class CounterInputStream.class\
          RangeGroup.class IntHash.class SGMLParser.class \
          ImageVault.class LED.class ComponentPlacer.class \
          FrameCounter.class VideoTimeBase.class FloatSlider.class \
          FixedPicturedPanel.class VariablePicturedPanel.class \
          FloatLabelButton.class FloatMinuteDisplay.class \
          MouseAwarePanel.class FloatNativeComponent.class ClockOverlay.class \
			 MemoryMeter.class

include ../Makefile.inc
