TOPDIR = ../../../..
LOCALDIR = imc/lecturnity/converter/wizard

CLASSES = RealConvertWizardData.class ConvertWizardData.class \
	LecturnityConvertWizardData.class \
	LecturnityExtendedDialog.class LecturnityStandardNavigationDialog.class \
	SelectPresentationWizardPanel.class \
	SelectActionWizardPanel.class LecturnityBandwidthWizardPanel.class \
	RealBandwidthWizardPanel.class LecturnitySettingsWizardPanel.class \
	LecturnityWriterWizardPanel.class \
	RealWriterWizardPanel.class VideoSelectWizardPanel.class \
	VideoSyncWizardPanel.class\
	LecturnityThumbnailWizardPanel.class \
	AbstractCdProjectWizardPanel.class CdProjectWizardPanel.class \
	CdProjectNewWizardPanel.class CdProjectSettingsWizardPanel.class \
	CdProjectPlayerWizardPanel.class CdProjectDocsWizardPanel.class \
	CdProjectWriterWizardPanel.class CdProjectTemplateWizardPanel.class \
	ExtendedVideoDialog.class ExtentOfConversionPanel.class \
	StreamingVideoSizePanel.class SlideSizePanel.class \
	StreamingLayoutPanel.class CustomSizePanel.class \
	RealVersionWizardPanel.class WmpConvertWizardData.class \
	ExportWizardPanel.class ExtendedSettingsDialog.class \
	WmpEncoderWizardPanel.class CdProjectCacheDialog.class \
	WmpWriterWizardPanel.class \
	StreamingVideoSizeDialog.class CustomStreamParameters.class \
	ScormTemplateWizardPanel.class WmpScormTemplateWizardPanel.class \
	RealScormTemplateWizardPanel.class StreamingConvertWizardData.class \
	FlashSettingsWizardPanel.class FlashWriterWizardPanel.class \
	ScormConvertWizardData.class FlashConvertWizardData.class \
	FlashScormTemplateWizardPanel.class FlashTemplateDialog.class \
	FlashSizeDialog.class FlashExtendedDialog.class \
	FlashAbstractExtendedDialog.class \
	FlashSizePanel.class FlashStandardNavigationDialog.class \
	VideoSettingsWizardPanel.class VideoWriterWizardPanel.class \
	VideoConvertWizardData.class \
	PublisherWizardData.class UploaderAccess.class \
	TargetChoiceWizardPanel.class TargetTypeWizardPanel.class \
   TargetUploadWizardPanel.class TargetDirsWizardPanel.class \
   WmpFileExtensionPanel.class
#  not used:
#	TargetTransferWizardPanel.class ProgressWizardPanel.class \
#	TargetStreamingWizardPanel.class

include ../Makefile.inc
