/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imc_epresenter_player_Manager */

#ifndef _Included_imc_epresenter_player_Manager
#define _Included_imc_epresenter_player_Manager
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: versionNumber */
#undef imc_epresenter_player_Manager_WARNING
#define imc_epresenter_player_Manager_WARNING 2L
#undef imc_epresenter_player_Manager_ERROR
#define imc_epresenter_player_Manager_ERROR 0L
/* Inaccessible static: dummy */
/* Inaccessible static: texts */
/* Inaccessible static: lastLoadDir */
/* Inaccessible static: libraryLoaded */
/*
 * Class:     imc_epresenter_player_Manager
 * Method:    launchFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imc_epresenter_player_Manager_launchFileNative
  (JNIEnv *env, jclass jc, jstring fileName);

#ifdef __cplusplus
}
#endif
#endif
