TOPDIR = ../../..
LOCALDIR = imc/lecturnity/util

SUBDIRS = wizards ui net/ftp

CLASSES = ImagePanel.class NativeUtils.class \
	VersionExtracter.class \
	FileUtils.class ColorManager.class \
	TemplateParser.class LecturnitySecurityException.class \
	InstallChecker.class ProgressListener.class \
	DelayedTimer.class ProgressListener.class PropertyHandler.class \
	SpecialTable.class CancelException.class \
	LogProgressListener.class SecurityUtils.class

include Makefile.inc
