# Makefile 24.6.00 

TOPDIR = ../../..
LOCALDIR = imc/epresenter/player

SUBDIRS = master whiteboard util audio ../filesdk ../../lecturnity/util ../media
CLASSES = Document.class SRStreamPlayer.class Daemon.class \
          FileClassLoader.class ApplicationPlayer.class Manager.class \
          Coordinator.class VideoPlayer.class JMFVideoPlayer.class \
          VideoPanel.class ThumbnailHelper.class \
          SearchHelper.class DocumentController.class HelpDisplay.class \
          GlobalMasterAndUI.class \
          GlobalMenuBar.class LayoutJune2002.class LayoutNov2006.class \
          CacheControl.class CacheBackend.class CacheSettings.class \
          CacheDialogs.class MyTableModel.class SpeedCheck.class \
          VideoVisiblePanel.class VideoAddPanel.class VideoLightPanel.class \
			 StopMarkPlayer.class

include Makefile.inc
