# Makefile 24.6.00 

TOPDIR = ../../../..
LOCALDIR = imc/epresenter/player/whiteboard

CLASSES = WhiteBoardPlayer.class EventQueue.class ComponentMover.class \
          ObjectQueue.class \
          VisualComponent.class Line.class Text.class Pointer.class \
          Character.class OutlineRectangle.class FilledRectangle.class \
          OutlineCircle.class FilledCircle.class Picture.class \
          FilledPolygon.class Freehand.class \
          ProgressListener.class InteractionArea.class ButtonArea.class \
			 DynamicComponent.class RadioDynamic.class TargetPoint.class \
			 TextFieldDynamic.class

include ../Makefile.inc
