# Makefile 24.6.00; modified 30.8.05

TOPDIR = ../../..
LOCALDIR = imc/lecturnity/info

SUBDIRS = 
CLASSES = LpdFile.class LpdTextTag.class LpdTextItemTag.class \
          ../../epresenter/player/whiteboard/Text.class \
			 AudioExtractor.class ../../epresenter/player/audio/SoundPlayer.class

include Makefile.inc
