TOPDIR = ../../../..
LOCALDIR = imc/lecturnity/util/ui

SUBDIRS = 

CLASSES = IconListObject.class IconListCellRenderer.class FileNode.class \
	DirJTree.class DirectoryChooser.class CustomJList.class \
        PopupHelp.class LayoutUtils.class LazyTextArea.class SplashScreen.class \
        SplashScreen2.class

include ../Makefile.inc
