# Makefile 02.03.01 

TOPDIR = ../../../..
LOCALDIR = imc/epresenter/player/audio

CLASSES = SoundPlayer.class AiffFileFormat.class AiffFileReader.class \
          AudioTransporter.class EOFListener.class \
          AQSFileWriter.class AQSFileReader.class AQSFileType.class \
          AQSInputStream.class BitOutputStream.class BitInputStream.class \
          CounterInputStream.class Audio2Wav.class

include ../Makefile.inc
