TOPDIR = ../../../..
LOCALDIR = imc/lecturnity/util/gif2png

SUBDIRS = ../ ../../../epresenter/filesdk ../../../epresenter/converter

CLASSES = BatchUpdater.class Gif2PngEngine.class \
	DocumentUpdater.class UpdaterSelectWizardPanel.class \
	UpdaterTargetWizardPanel.class UpdaterUpdateWizardPanel.class

GIF2PNGVERSION = `cat imc/lecturnity/util/gif2png/VERSION`
SCOREGIF2PNGVERSION = `cat imc/lecturnity/util/gif2png/VERSION | tr \. _`

include ../Makefile.inc
