//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Podcaster.rc
//
#define IDS_ERROR                       3
#define IDS_ERROR_INSTALLATION          4
#define IDS_ERROR_LANGUAGE              5
#define IDS_ERROR_SET_LANGUAGE          6
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_PODCASTER_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDD_SETTINGS_DIALOG             129
#define IDD_PASSWORD_DIALOG             131
#define IDI_SETTINGS                    134
#define IDI_PASSWORD                    135
#define IDD_LRD_DIALOG                  144
#define IDD_MP4_DIALOG                  145
#define IDI_PODCASTER                   146
#define IDD_CHANNELMETADATA             147
#define IDD_MAINSETTINGS                148
#define IDD_METADATA_PAGE               149
#define IDD_TRANSFER_PAGE               150
#define IDD_CHANNELMETADATA2            151
#define IDD_SETTINGS_DIALOG2            152
#define IDD_LRD_DIALOG2                 153
#define IDR_ACTIVECHANNEL               154
#define IDB_RADIOBUTTON                 155
#define IDD_MP4EXISTS                   156
#define IDD_NEWMP4                      157
#define IDD_WAIT_DIALOG                 158
#define IDS_FTPERROR                    701
#define IDS_SUCCESS                     702
#define IDS_ERRDIR1                     703
#define IDS_ERRDIR2                     708
#define IDS_NOXMLFILE                   709
#define IDS_ERRUPLOADXML                710
#define IDS_ERROPENFILE                 711
#define IDS_ERR_FTP_CREATE_FILE         712
#define IDS_INVPATH                     713
#define IDS_NOTEQUALS                   714
#define IDS_ERRPARSE                    720
#define IDS_ERRPARSE2                   721
#define IDC_SERVICE                     1000
#define IDE_XMLURL                      1001
#define IDE_HOST                        1002
#define IDC_PORT                        1003
#define IDE_CHANNELDIR                  1004
#define IDE_MP4URL                      1005
#define IDC_PROGRESS                    1006
#define IDE_MP4DIR                      1007
#define IDC_BROWSE                      1008
#define IDC_SAVE_PASSWORD               1009
#define IDC_OPTION2                     1010
#define IDC_OPTION1                     1011
#define IDC_TEXTLOGO                    1012
#define IDC_SETTINGS                    1013
#define IDL_TO                          1014
#define IDC_USERNAME                    1015
#define IDC_PASSWORD                    1016
#define IDC_MP4FILE                     1017
#define IDE_LRDFILE                     1018
#define IDC_TITLE                       1019
#define IDC_AUTHOR                      1020
#define IDC_MP4DOC                      1021
#define IDC_SSHV                        1022
#define IDB_NEW                         1023
#define IDC_IPV                         1024
#define IDB_IMPORT                      1025
#define IDL_COMPRESSION                 1026
#define IDB_REMOVE                      1027
#define IDL_PKK                         1028
#define IDB_DELETE                      1029
#define IDE_TITLE                       1030
#define IDE_SUBTITLE                    1031
#define IDC_CHANNELLIST                 1032
#define IDC_PAGES                       1033
#define IDE_AUTHOR                      1034
#define IDE_DESCRIPTION                 1035
#define IDE_SUMARRY                     1037
#define IDB_SETINGS                     1038
#define IDE_LANGUAGE                    1039
#define IDB_PODCAST                     1040
#define IDE_COPYRIGHT                   1041
#define IDB_BROWSE                      1042
#define IDC_CHANNEL                     1043
#define IDE_OWNER                       1044
#define IDC_WEBURL                      1045
#define IDC_HOSTNAME                    1046
#define IDC_SAVE                        1047
#define IDC_XMLDIR                      1048
#define IDC_MP4DIR                      1049
#define IDE_KEYWORDS                    1050
#define IDC_SSH                         1051
#define IDC_IP                          1052
#define IDC_COMPRESSION                 1053
#define IDC_PKF                         1054
#define IDC_SUBTITLE                    1055
#define IDC_DESCRIPTION                 1056
#define IDC_SUMMARY                     1057
#define IDC_LANGUAGE                    1058
#define IDC_COPYRIGHT                   1059
#define IDC_OWNER                       1060
#define IDC_EMAIL                       1061
#define IDC_LINK                        1062
#define IDC_WEBMASTER                   1063
#define IDC_EXPLICIT                    1064
#define IDC_KEYWORDS                    1065
#define IDL_FROM                        1066
#define IDE_LINK                        1067
#define IDE_WEBMASTER                   1068
#define IDE_EXPLICIT                    1069
#define IDL_TITLE                       1070
#define IDL_SUBTITLE                    1071
#define IDL_AUTHOR                      1072
#define IDL_DESCRIPTION                 1073
#define IDL_SUMMARY                     1074
#define IDL_LANGUAGE                    1075
#define IDL_COPYRIGHT                   1076
#define IDL_OWNER                       1077
#define IDL_MAIL                        1078
#define IDL_LINK                        1079
#define IDL_WEBMASTER                   1080
#define IDL_EXPLICIT                    1081
#define IDL_KEYWORDS                    1082
#define IDE_MAIL                        1083
#define IDL_USERNAME                    1084
#define IDL_PASSWORD                    1085
#define IDL_PODCASTDOC                  1086
#define IDC_PODCASTDOC                  1087
#define IDL_CHANNEL                     1088
#define IDL_SERVICE                     1089
#define IDL_MP4URL                      1090
#define IDG_SERVER                      1091
#define IDL_SERVER                      1092
#define IDL_PORT                        1093
#define IDL_SAVEPSWD                    1094
#define IDL_CHANNELDIR                  1095
#define IDL_MP4DIR                      1096
#define IDL_SSHV                        1097
#define IDL_IPV                         1098
#define IDE_PORT                        1099
#define IDE_USERNAME                    1100
#define IDE_PASSWORD                    1101
#define IDB_CHANGE                      1102
#define IDL_CHANNELS                    1103
#define IDL_LRDDOC                      1104
#define IDL_METADATA                    1105
#define IDC_BARBOTTOM                   1106
#define IDL_ACTIVE                      1106
#define IDL_TITLE2                      1107
#define IDT_METADATA                    1108
#define IDOVER                          1109
#define IDT_TRANSFER                    1110
#define IDC_EDIT1                       1111
#define IDM_SSHDLL                      1112
#define IDL_L1                          1113
#define IDM_ACTIVE                      1114
#define IDL_L2                          1115
#define IDM_CONFIRMREMOVE               1116
#define IDL_L3                          1117
#define IDM_CONFIRMDELETE               1118
#define IDL_L4                          1119
#define IDL_L5                          1120
#define IDL_L6                          1121
#define IDL_L7                          1122
#define IDC_WAIT_MESSAGE                1122
#define IDL_NF1                         1123
#define IDL_NF2                         1124
#define IDMODY                          1125
#define IDS_UPDATE_CHANNEL              1126
#define IDS_CONNECTING_SERVER           1127
#define IDS_WARNING_WHITESPACE          1128
#define IDS_ERR_MP4URL                  1129
#define IDS_WAIT_MESSAGE                1130

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        159
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1123
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
