TOPDIR = ../../../..
LOCALDIR = imc/epresenter/filesdk/util

CLASSES = XmlParser.class XmlFormatException.class Logger.class \
          CountInputStream.class ClickHandler.class ByteCounter.class \
			 Localizer.class

include ../Makefile.inc
