/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imc_epresenter_media_codec_video_LsgcDecoder */

#ifndef _Included_imc_epresenter_media_codec_video_LsgcDecoder
#define _Included_imc_epresenter_media_codec_video_LsgcDecoder
#ifdef __cplusplus
extern "C" {
#endif
#undef imc_epresenter_media_codec_video_LsgcDecoder_DEBUG
#define imc_epresenter_media_codec_video_LsgcDecoder_DEBUG 0L
/* Inaccessible static: jdkInit */
/* Inaccessible static: forName3ArgsM */
/* Inaccessible static: getSystemClassLoaderM */
/* Inaccessible static: systemClassLoader */
/* Inaccessible static: getContextClassLoaderM */
/* Inaccessible static: class_00024java_00024lang_00024String */
/* Inaccessible static: class_00024java_00024lang_00024ClassLoader */
/* Inaccessible static: class_00024java_00024lang_00024Class */
/* Inaccessible static: class_00024java_00024lang_00024Thread */
/* Inaccessible static: libraryLoaded_ */
/* Inaccessible static: processLock_ */
/*
 * Class:     imc_epresenter_media_codec_video_LsgcDecoder
 * Method:    nDecompressBegin
 * Signature: (Lcom/sun/media/vfw/BitMapInfo;Lcom/sun/media/vfw/BitMapInfo;)Z
 */
JNIEXPORT jlong JNICALL Java_imc_epresenter_media_codec_video_LsgcDecoder_nDecompressBegin
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     imc_epresenter_media_codec_video_LsgcDecoder
 * Method:    nDecompress
 * Signature: (JLcom/sun/media/vfw/BitMapInfo;Ljava/lang/Object;JLcom/sun/media/vfw/BitMapInfo;Ljava/lang/Object;J)I
 */
JNIEXPORT jint JNICALL Java_imc_epresenter_media_codec_video_LsgcDecoder_nDecompress
  (JNIEnv *, jobject, jlong, jlong, jobject, jobject, jlong, jobject, jobject, jlong);

/*
 * Class:     imc_epresenter_media_codec_video_LsgcDecoder
 * Method:    nDecompressEnd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imc_epresenter_media_codec_video_LsgcDecoder_nDecompressEnd
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
