/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imc_lecturnity_converter_wizard_UploaderAccess */

#ifndef _Included_imc_lecturnity_converter_wizard_UploaderAccess
#define _Included_imc_lecturnity_converter_wizard_UploaderAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imc_lecturnity_converter_wizard_UploaderAccess
 * Method:    ShowYtTransferConfigDialog
 * Signature: (Limc/lecturnity/converter/wizard/UploaderAccess/YtTransferSettings;Ljava/awt/Window;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_wizard_UploaderAccess_ShowYtTransferConfigDialog
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     imc_lecturnity_converter_wizard_UploaderAccess
 * Method:    GetYtTransferData
 * Signature: (Limc/lecturnity/converter/wizard/UploaderAccess/YtTransferSettings;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_wizard_UploaderAccess_GetYtTransferData
  (JNIEnv *, jclass, jobject);
/*
 * Class:     imc_lecturnity_converter_wizard_UploaderAccess
 * Method:    ShowTransferConfigDialog
 * Signature: (Limc/lecturnity/converter/wizard/UploaderAccess/TransferSettings;Ljava/awt/Window;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_wizard_UploaderAccess_ShowTransferConfigDialog
  (JNIEnv *, jclass, jobject, jobject, jboolean jbIsSlidestar);

/*
 * Class:     imc_lecturnity_converter_wizard_UploaderAccess
 * Method:    GetTransferData
 * Signature: (Limc/lecturnity/converter/wizard/UploaderAccess/TransferSettings;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_wizard_UploaderAccess_GetTransferData
  (JNIEnv *, jclass, jobject);

/*
 * Class:     imc_lecturnity_converter_wizard_UploaderAccess
 * Method:    ShowPodcastConfigDialog
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Limc/lecturnity/converter/wizard/UploaderAccess/TransferSettings;Limc/lecturnity/converter/wizard/UploaderAccess/TransferSettings;Ljava/awt/Window;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_wizard_UploaderAccess_ShowPodcastConfigDialog
  (JNIEnv *, jclass, jstring, jstring, jstring, jobject, jobject, jobject);

/*
 * Class:     imc_lecturnity_converter_wizard_UploaderAccess
 * Method:    GetPodcastData
 * Signature: (Limc/lecturnity/converter/wizard/UploaderAccess/StringContainer;Limc/lecturnity/converter/wizard/UploaderAccess/StringContainer;Limc/lecturnity/converter/wizard/UploaderAccess/StringContainer;Limc/lecturnity/converter/wizard/UploaderAccess/TransferSettings;Limc/lecturnity/converter/wizard/UploaderAccess/TransferSettings;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_wizard_UploaderAccess_GetPodcastData
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     imc_lecturnity_converter_wizard_UploaderAccess
 * Method:    IsNotEmptyDir
 * Signature: (Ljava/lang/String;Limc/lecturnity/converter/wizard/UploaderAccess/TransferSettings;Ljava/awt/Window;)Z
 */
JNIEXPORT jboolean JNICALL Java_imc_lecturnity_converter_wizard_UploaderAccess_IsNotEmptyDir
  (JNIEnv *, jclass, jstring, jobject, jobject);

/*
 * Class:     imc_lecturnity_converter_wizard_UploaderAccess
 * Method:    IsSlidestar
 * Signature: (Ljava/lang/String;Limc/lecturnity/converter/wizard/UploaderAccess/TransferSettings;Ljava/awt/Window;)Z
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_wizard_UploaderAccess_IsSlidestar
  (JNIEnv *env, jclass, jboolean jbIsSlidestar);

/*
 * Class:     imc_lecturnity_converter_wizard_UploaderAccess
 * Method:    CheckTargetExists
 * Signature: (Ljava/lang/String;Limc/lecturnity/converter/wizard/UploaderAccess/TransferSettings;Ljava/awt/Window;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_wizard_UploaderAccess_CheckTargetExists
  (JNIEnv *, jclass, jstring, jobject, jobject);

/*
 * Class:     imc_lecturnity_converter_wizard_UploaderAccess
 * Method:    CheckUpload
 * Signature: (Limc/lecturnity/converter/wizard/UploaderAccess/TransferSettings;Ljava/awt/Window;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_wizard_UploaderAccess_CheckUpload
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     imc_lecturnity_converter_wizard_UploaderAccess
 * Method:    CheckYtUpload
 * Signature: (Limc/lecturnity/converter/wizard/UploaderAccess/YtTransferSettings;Ljava/awt/Window;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_wizard_UploaderAccess_CheckYtUpload
  (JNIEnv *, jclass, jobject, jstring, jobject);

/*
 * Class:     imc_lecturnity_converter_wizard_UploaderAccess
 * Method:    StartUpload
 * Signature: (Limc/lecturnity/converter/wizard/UploaderAccess/TransferSettings;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_wizard_UploaderAccess_StartUpload
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     imc_lecturnity_converter_wizard_UploaderAccess
 * Method:    StartYtUpload
 * Signature: (Limc/lecturnity/converter/wizard/UploaderAccess/YtTransferSettings;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_wizard_UploaderAccess_StartYtUpload
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     imc_lecturnity_converter_wizard_UploaderAccess
 * Method:    StartPodcast
 * Signature: (Ljava/lang/String;Ljava/lang/String;Limc/lecturnity/converter/wizard/UploaderAccess/TransferSettings;Limc/lecturnity/converter/wizard/UploaderAccess/TransferSettings;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_wizard_UploaderAccess_StartPodcast
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jobject, jobject, jobjectArray);

/*
 * Class:     imc_lecturnity_converter_wizard_UploaderAccess
 * Method:    GetUploadProgress
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_imc_lecturnity_converter_wizard_UploaderAccess_GetUploadProgress
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_wizard_UploaderAccess
 * Method:    GetLastError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_converter_wizard_UploaderAccess_GetLastError
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_wizard_UploaderAccess
 * Method:    CancelSession
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imc_lecturnity_converter_wizard_UploaderAccess_CancelSession
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_wizard_UploaderAccess
 * Method:    StartSession
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imc_lecturnity_converter_wizard_UploaderAccess_StartSession
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_wizard_UploaderAccess
 * Method:    FinishSession
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imc_lecturnity_converter_wizard_UploaderAccess_FinishSession
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
