//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Uploader.rc
//
#define IDOK                            1
#define IDCANCEL                        2
#define IDS_ERROR                       3
#define IDS_ERROR_INSTALLATION          4
#define IDS_ERROR_LANGUAGE              5
#define IDS_ERROR_SET_LANGUAGE          6
#define IDS_ERR_NO_FILES                7
#define IDS_WRONG_PASSWORD              8
#define IDI_UPLOADER                    9
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TRANSFER_PROGRESS_DIALOG    102
#define IDD_PASSWORD_DIALOG             131
#define IDD_CHANNELMETADATA             147
#define IDD_MAINSETTINGS                148
#define IDD_METADATA_PAGE               149
#define IDD_TRANSFER_PAGE               150
#define IDD_MAIN_DIALOG                 153
#define IDS_PODCASTER                   154
#define IDD_MP4EXISTS                   156
#define IDD_NEWMP4                      157
#define IDD_WAIT_DIALOG                 158
#define IDD_TRANSFER_CONFIG_DIALOG      159
#define IDS_FTPERROR                    701
#define IDS_SUCCESS                     702
#define IDS_ERRDIR1                     703
#define IDS_ERRDIR2                     708
#define IDS_ERRUPLOADXML                710
#define IDS_ERROPENFILE                 711
#define IDS_ERR_FTP_CREATE_FILE         712
#define IDS_INVPATH                     713
#define IDS_NOTEQUALS                   714
#define IDS_ERRPARSE                    720
#define IDS_ERRPARSE2                   721
#define IDC_SERVICE                     1000
#define IDE_HOST                        1002
#define IDE_URL                         1003
#define IDC_PROGRESS                    1006
#define IDE_DIRECTORY                   1009
#define IDR_EXPLICIT_METADATA           1010
#define IDR_LRD_METADATA                1011
#define IDL_TO                          1014
#define IDC_USERNAME_MEDIA              1017
#define IDE_LRD_FILE                    1018
#define IDC_TITLE                       1019
#define IDC_AUTHOR                      1020
#define IDB_NEW                         1023
#define IDB_IMPORT                      1025
#define IDB_REMOVE                      1027
#define IDC_CHANNEL                     1028
#define IDB_DELETE                      1029
#define IDE_TITLE                       1030
#define IDE_SUBTITLE                    1031
#define IDC_CHANNELLIST                 1032
#define IDC_PAGES                       1033
#define IDE_AUTHOR                      1034
#define IDE_DESCRIPTION                 1035
#define IDE_SUMARRY                     1037
#define IDE_LANGUAGE                    1039
#define IDB_PODCAST                     1040
#define IDE_COPYRIGHT                   1041
#define IDB_BROWSE                      1042
#define IDB_BROWSE_LRD                  1043
#define IDE_OWNER                       1044
#define IDC_WEBURL                      1045
#define IDC_XMLDIR                      1048
#define IDC_MP4DIR                      1049
#define IDE_KEYWORDS                    1050
#define IDC_BARBOTTOM                   1054
#define IDC_SUBTITLE                    1055
#define IDC_DESCRIPTION                 1056
#define IDC_SUMMARY                     1057
#define IDC_LANGUAGE                    1058
#define IDC_COPYRIGHT                   1059
#define IDC_OWNER                       1060
#define IDC_EMAIL                       1061
#define IDC_LINK                        1062
#define IDC_WEBMASTER                   1063
#define IDC_EXPLICIT                    1064
#define IDC_KEYWORDS                    1065
#define IDL_FROM                        1066
#define IDE_LINK                        1067
#define IDE_WEBMASTER                   1068
#define IDE_EXPLICIT                    1069
#define IDL_TITLE                       1070
#define IDL_SUBTITLE                    1071
#define IDL_AUTHOR                      1072
#define IDL_DESCRIPTION                 1073
#define IDL_SUMMARY                     1074
#define IDL_LANGUAGE                    1075
#define IDL_COPYRIGHT                   1076
#define IDL_OWNER                       1077
#define IDL_MAIL                        1078
#define IDL_LINK                        1079
#define IDL_WEBMASTER                   1080
#define IDL_EXPLICIT                    1081
#define IDL_KEYWORDS                    1082
#define IDE_MAIL                        1083
#define IDL_USERNAME                    1084
#define IDL_PASSWORD                    1085
#define IDL_HOST                        1086
#define IDE_PODCAST_DOC                 1087
#define IDL_CHANNEL                     1088
#define IDL_SERVICE                     1089
#define IDL_MP4URL                      1090
#define IDG_SERVER                      1091
#define IDL_PORT                        1093
#define IDL_SAVEPSWD                    1094
#define IDL_CHANNELDIR                  1095
#define IDL_MP4DIR                      1096
#define IDL_SERVICE_MEDIA               1097
#define IDL_HOST_MEDIA                  1098
#define IDE_PORT                        1099
#define IDE_USERNAME                    1100
#define IDE_PASSWORD                    1101
#define IDB_CHANGE                      1102
#define IDL_CHANNELS                    1103
#define IDL_ACTIVE                      1106
#define IDL_TITLE2                      1107
#define IDT_METADATA                    1108
#define IDOVER                          1109
#define IDT_TRANSFER                    1110
#define IDC_EDIT_FILE                   1111
#define IDM_SSHDLL                      1112
#define IDL_L1                          1113
#define IDM_ACTIVE                      1114
#define IDL_L2                          1115
#define IDM_CONFIRMREMOVE               1116
#define IDL_L3                          1117
#define IDM_CONFIRMDELETE               1118
#define IDL_L4                          1119
#define IDL_L5                          1120
#define IDL_L6                          1121
#define IDL_L7                          1122
#define IDL_NF1                         1123
#define IDL_NF2                         1124
#define IDMODY                          1125
#define IDS_UPDATE_CHANNEL              1126
#define IDS_CONNECTING_SERVER           1127
#define IDS_WARNING_WHITESPACE          1128
#define IDS_ERR_MP4URL                  1129
#define IDC_WAIT_MESSAGE                1130
#define IDL_DIRECTORY                   1131
#define IDC_ST_MP4                      1132
#define IDC_GROUP_METADATA              7000
#define IDC_GROUP_TRANSFER              7001
#define IDS_PWD_SERVER                  7003
#define IDS_PWD_DIALOG_DLL              7004
#define IDB_RADIOBUTTON                 7005
#define IDD_YT_MAIN_DIALOG              7006
#define IDL_URL                         7008
#define IDC_ST_LZP                      7009
#define IDB_BROWSE_DOC                  7010
#define IDL_PODCAST_DOC                 7011
#define IDD_YT_TRANSFER_DIALOG          7012
#define IDL_EXPLICIT_METADATA           7013
#define IDB_SETTINGS                    7014
#define IDL_LRD_METADATA                7015
#define IDC_SERVICE_CHANNEL             7022
#define IDC_SERVICE_MEDIA               7023
#define IDC_PORT_CHANNEL                7024
#define IDC_PORT_MEDIA                  7025
#define IDC_USERNAME_CHANNEL            7026
#define IDC_PASSWORD_CHANNEL            7027
#define IDC_PASSWORD_MEDIA              7028
#define IDC_HOSTNAME_CHANNEL            7029
#define IDC_HOSTNAME_MEDIA              7030
#define IDC_SAVE_CHANNEL                7031
#define IDC_SAVE_MEDIA                  7032
#define IDL_USERNAME_MEDIA              7033
#define IDL_PASSWORD_MEDIA              7034
#define IDL_SAVEPSWD_MEDIA              7035
#define IDL_PORT_MEDIA                  7036
#define IDB_CHANGE_MEDIA                7038
#define IDL_STATUS                      7039
#define IDS_TEMPORARY                   7040
#define IDL_PODCAST_CHANNEL             7041
#define IDL_PWD_SERVER                  7042
#define IDL_PODCAST_MEDIA_SERVER        7043
#define IDC_STATIC_SERVER               7043
#define IDS_YES                         7044
#define IDS_NO                          7045
#define IDS_CHANNEL_EXISTS              7046
#define IDC_STATIC_YT_DESCRIPTION       7047
#define IDC_STATIC_YT_KEYWORDS          7048
#define IDC_STATIC_YT_CATEGORY          7049
#define IDC_STATIC_YT_PRIVACY           7050
#define IDC_EDIT_YT_FILE                7059
#define IDC_YT_BROWSE_BUTTON            7060
#define IDC_BUTTON_YT_AUTH              7061
#define IDC_EDIT_DUMMY                  7062
#define IDC_YT_UPLOAD_BUTTON            7064
#define IDC_EDIT_DMY2                   7065
#define IDC_BUTTON1                     7066
#define IDC_STATIC_YT_USERNAME          7074
#define IDC_STATIC_YT_PASSWORD          7075
#define IDC_STATIC_YT_TITLE             7076
#define IDS_YT_ERR_TOO_LONG             7081
#define IDS_YT_ERR_TOO_BIG              7082
#define IDS_YT_ERR_AUTH_BAD_AUTH        7083
#define IDS_YT_ERR_AUTH_NOT_VERIF       7084
#define IDS_YT_ERR_AUTH_TERMS_NAGREED   7085
#define IDS_YT_ERR_AUTH_CAPCHA_REQ      7086
#define IDS_YT_ERR_AUTH_ACCOUNT_DEL     7087
#define IDS_YT_ERR_AUTH_ACCOUNT_DIS     7088
#define IDS_YT_ERR_AUTH_SERVICE_DIS     7089
#define IDS_YT_ERR_AUTH_SERVICE_UNAV    7090
#define IDS_YT_ERR_UNKNOWN              7091
#define IDS_YTT_TITLE                   7095
#define IDS_YTT_DESCRIPTION             7096
#define IDS_YTT_KEYWORD                 7097
#define IDS_YTT_KEYWORD_NUMBER          7098
#define IDS_YTU_DEPRECATED              7101
#define IDS_YTU_INVALID_CHAR            7102
#define IDS_YTU_TOO_MANY_CALLS          7103
#define IDS_YTU_TOO_MANY_ENTRIES        7104
#define IDS_YTU_TOKEN_INVALID           7105
#define IDS_YTU_TOKEN_EXPIRED           7106
#define IDS_YTU_SERVICE                 7107
#define IDS_YTU_WRONG_PARAMS            7108

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        7008
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         7067
#define _APS_NEXT_SYMED_VALUE           7000
#endif
#endif
