/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_media_renderer_video_GDIRenderer */

#ifndef _Included_com_sun_media_renderer_video_GDIRenderer
#define _Included_com_sun_media_renderer_video_GDIRenderer
#ifdef __cplusplus
extern "C" {
#endif
#undef com_sun_media_renderer_video_GDIRenderer_DEBUG
#define com_sun_media_renderer_video_GDIRenderer_DEBUG 0L
/* Inaccessible static: jdkInit */
/* Inaccessible static: forName3ArgsM */
/* Inaccessible static: getSystemClassLoaderM */
/* Inaccessible static: systemClassLoader */
/* Inaccessible static: getContextClassLoaderM */
/* Inaccessible static: class_00024java_00024lang_00024Class */
/* Inaccessible static: class_00024java_00024lang_00024String */
/* Inaccessible static: class_00024java_00024lang_00024ClassLoader */
/* Inaccessible static: class_00024java_00024lang_00024Thread */
/* Inaccessible static: available */
/*
 * Class:     com_sun_media_renderer_video_GDIRenderer
 * Method:    gdiInitialize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_sun_media_renderer_video_GDIRenderer_gdiInitialize
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_media_renderer_video_GDIRenderer
 * Method:    gdiSetComponent
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sun_media_renderer_video_GDIRenderer_gdiSetComponent
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sun_media_renderer_video_GDIRenderer
 * Method:    gdiSetOutputSize
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sun_media_renderer_video_GDIRenderer_gdiSetOutputSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_sun_media_renderer_video_GDIRenderer
 * Method:    gdiDraw
 * Signature: (Ljava/lang/Object;JIIIIIIIIIIZI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sun_media_renderer_video_GDIRenderer_gdiDraw
  (JNIEnv *, jobject, jobject, jlong, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jboolean, jint);

/*
 * Class:     com_sun_media_renderer_video_GDIRenderer
 * Method:    gdiFree
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_sun_media_renderer_video_GDIRenderer_gdiFree
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
