/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imc_lecturnity_util_ui_SplashScreen2 */

#ifndef _Included_imc_lecturnity_util_ui_SplashScreen2
#define _Included_imc_lecturnity_util_ui_SplashScreen2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imc_lecturnity_util_ui_SplashScreen2
 * Method:    Show
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imc_lecturnity_util_ui_SplashScreen2_Show
  (JNIEnv *, jobject);

/*
 * Class:     imc_lecturnity_util_ui_SplashScreen2
 * Method:    ShowAsAbout
 * Signature: (Ljava/awt/Window;)V
 */
JNIEXPORT void JNICALL Java_imc_lecturnity_util_ui_SplashScreen2_ShowAsAbout
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imc_lecturnity_util_ui_SplashScreen2
 * Method:    Hide
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imc_lecturnity_util_ui_SplashScreen2_Hide
  (JNIEnv *, jobject);

/*
 * Class:     imc_lecturnity_util_ui_SplashScreen2
 * Method:    GetScreenBounds
 * Signature: ()Ljava/awt/Rectangle;
 */
JNIEXPORT jobject JNICALL Java_imc_lecturnity_util_ui_SplashScreen2_GetScreenBounds
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
