/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imc_lecturnity_converter_ScreengrabbingExtended */

#ifndef _Included_imc_lecturnity_converter_ScreengrabbingExtended
#define _Included_imc_lecturnity_converter_ScreengrabbingExtended
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imc_lecturnity_converter_ScreengrabbingExtended
 * Method:    runPostProcessing
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_imc_lecturnity_converter_ScreengrabbingExtended_runPostProcessing
  (JNIEnv *, jclass, jstring);

JNIEXPORT jboolean JNICALL Java_imc_lecturnity_converter_ScreengrabbingExtended_removeStructure
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
