/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imc_lecturnity_converter_ProfiledSettings */

#ifndef _Included_imc_lecturnity_converter_ProfiledSettings
#define _Included_imc_lecturnity_converter_ProfiledSettings
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imc_lecturnity_converter_ProfiledSettings
 * Method:    GetActiveProfile
 * Signature: ()Limc/lecturnity/converter/ProfiledSettings/ProfileInfo;
 */
JNIEXPORT jobject JNICALL Java_imc_lecturnity_converter_ProfiledSettings_GetActiveProfile
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_ProfiledSettings
 * Method:    ShowManageDialog
 * Signature: (Ljavax/swing/JFrame;Ljava/lang/String;)Limc/lecturnity/converter/ProfiledSettings/ProfileInfo;
 */
JNIEXPORT jobject JNICALL Java_imc_lecturnity_converter_ProfiledSettings_ShowFormatDialog
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     imc_lecturnity_converter_ProfiledSettings
 * Method:    SignalCancel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imc_lecturnity_converter_ProfiledSettings_SignalCancel
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_ProfiledSettings
 * Method:    WriteToProfile
 * Signature: (Limc/lecturnity/converter/ProfiledSettings/ProfileInfo;[Limc/lecturnity/converter/ProfiledSettings/ProfileEntry;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_ProfiledSettings_WriteToProfile
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     imc_lecturnity_converter_ProfiledSettings
 * Method:    ReadFromProfile
 * Signature: (Limc/lecturnity/converter/ProfiledSettings/ProfileInfo;)[Limc/lecturnity/converter/ProfiledSettings/ProfileEntry;
 */
JNIEXPORT jobjectArray JNICALL Java_imc_lecturnity_converter_ProfiledSettings_ReadFromProfile
  (JNIEnv *, jobject, jobject);

/*
 * Class:     imc_lecturnity_converter_ProfiledSettings
 * Method:    GetLastProfileErrorCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_ProfiledSettings_GetLastProfileErrorCode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
