//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by lsutl32.rc
//
#define IDS_CONFIRM_DELETE_CAPTION      46
#define IDS_CONFIRM_DELETE_TEXT         47
#define IDS_PPR_FILEFILTER              49
#define IDS_ERROR_ACTION_NEW            68
#define IDS_ERROR_ACTION_EDIT           69
#define IDS_ERROR_ACTION_IMPORT         70
#define IDS_ERROR_ACTION_ACCESS         71
#define IDS_ERROR_APPLICATIONDIR        74
#define IDS_ERROR_CREATESUBDIR          75
#define IDS_ERROR_PERMISSION            76
#define IDS_ERROR_JNI_INSERT_NEW        77
#define IDS_ERROR_NOTINLIST_EDIT        79
#define IDS_ERROR_JNI_INSERT_EDIT       80
#define IDS_ERROR_DELETE_FILE           81
#define IDS_ERROR_FILENOTFOUND_IMPORT   82
#define IDS_ERROR_PERMISSION_READ_IMPORT 83
#define IDS_ERROR_READ_IMPORT           84
#define IDS_ERROR_FORMAT_IMPORT         85
#define IDS_ERROR_CREATESUBDIR_EXPORT   86
#define IDS_ERROR_PERMISSION_EXPORT     87
#define IDS_ERROR_WRITE_EXPORT          88
#define IDS_ERROR_JNI_MAINWINDOW        89
#define IDS_ERROR_WRITE_ACTIVEPROFILE   91
#define IDS_ERROR_WRITE                 92
#define IDS_ERROR_ACTION_RENAME         93
#define IDS_DEFAULT_NAME                109
#define IDD_PROFILE_MANAGER             117
#define IDD_PP_PROGRESS                 187
#define IDS_PROFILE_NAME                200
#define IDS_YOUTUBE_DIALOG              201
#define IDS_SLIDESTAR_DIALOG            202
#define IDS_KEY_MISSING                 203
#define IDS_KEY_INVALID                 204
#define IDS_KEY_FAILURE                 205
#define IDS_KEY_SUCCESS                 206
#define IDD_SINGLE_PROGRESS_DIALOG      1001
#define IDC_PP_PROGRESS1                1034
#define IDC_PP_PROGRESS2                1035
#define IDC_EP_OVERALL                  1036
#define IDC_EP_PARTICULAR               1037
#define IDS_MANUAL_CONFIGURATION        1038
#define IDC_CANCEL                      1044
#define IDC_PAGE                        1045
#define IDC_CHAPTER                     1046
#define IDC_LATER                       1047
#define IDS_OK                          1048
#define IDC_STRUCTURING                 2000
#define IDC_IMAGING                     2001
#define IDC_FULLTEXT                    2002
#define IDC_COMPLETED                   2003
#define IDS_PUBLISHINGTITLE             2004
#define IDS_PUBLISHINGSUBTITLE          2005
#define IDS_LECTURNITY                  2006
#define IDS_PROFILE_MANAGER             2007
#define IDS_NAME_CAPTION                2008
#define IDS_RESERVED_CHARS              2009
#define IDC_RENAME_PROFILE              2102
#define IDC_DELETE_PROFILE              2103
#define IDC_NEW_PROFILE                 2104
#define IDC_EDIT_PROFILE                2105
#define IDC_ACTIVATE_PROFILE            2106
#define IDC_DEACTIVATE_PROFILE          2107
#define IDC_IMPORT_PROFILE              2108
#define IDC_EXPORT_PROFILE              2110
#define IDS_ACTIVATED                   2123
#define IDS_TARGET_FORMAT               2125
#define IDC_PROFILE_LIST                2134
#define IDS_STORAGE                     2152
#define IDC_EDIT_PROFILENAME            2153
#define IDC_LABEL_PROFILENAME           2154
#define IDD_PROFILE_SETNAME             2155
#define IDS_ERROR_CAPTION               2156
#define IDS_EXPORT_LPD                  2157
#define IDS_EXPORT_WM                   2158
#define IDS_EXPORT_REAL                 2159
#define IDS_EXPORT_FLASH                2160
#define IDS_EXPORT_IPOD                 2161
#define IDS_SD_SLIDESTAR                2162
#define IDS_SD_PODCAST                  2163
#define IDS_SD_WEBSERVER                2164
#define IDS_SD_LOCAL                    2165
#define IDS_SD_WEBSERVER_FT             2166
#define IDS_SD_WEB_STREAMING            2167
#define IDS_SD_WEB_STREAMING_FT         2168
#define IDS_SD_FILE_SERVER              2169
#define IDS_ERROR_NO_LRD                2170
#define IDS_ERROR_NOADMIN               2171
#define IDS_CAPTION_NOPERMISSION        2172
#define IDS_ERROR_EDIT_NOLRD            2173
#define IDS_NO_PROFILE_SELECTED         2174
#define IDS_LABEL_EDIT                  2175
#define IDS_YES                         2176
#define IDS_LICENSE_KEY                 2177
#define IDD_STRUCTEDITOR_DIALOG         4000
#define IDC_STRUCTEDITOR_HEADER         4001
#define IDC_STRUCTEDITOR_CHAPTER        4002
#define IDS_STRUCTEDITOR_DELETE         4003
#define IDS_STRUCTEDITOR_MODIFY_TITLE   4004
#define IDS_STRUCTEDITOR_CONFIRM_DELETE 4005
#define IDS_STRUCTEDITOR_CONFIRM_QUESTION 4006
#define IDS_STRUCTEDITOR_OK             4007
#define IDS_STRUCTEDITOR_CANCEL         4008
#define IDC_STRUCTEDITOR_HINT           4009
#define IDB_DELETE_BUTTON               4010
#define IDB_DELETE_BUTTON_SEL           4011
#define IDB_DELETE_BUTTON_DISABLED      4012
#define IDR_LANGUAGE_DE                 4012
#define IDR_LANGUAGE_EN                 4013
#define IDR_LANGUAGE_VI                 4014
#define IDD_PUBLISHING_FORMAT           4015
#define IDD_MANUALCON_FIGURATION        4016
#define IDC_PUBLISHINGTITLE             4018
#define IDB_REALMEDIA                   4019
#define IDC_FORMAT_GROUP                4020
#define IDB_WINDOWSMEDIA                4021
#define IDC_ICON_RM                     4022
#define IDB_LPD                         4023
#define IDC_FORMAT_RM                   4024
#define IDC_ICON_WM                     4025
#define IDC_FORMAT_LPD                  4026
#define IDC_ICON_LPD                    4027
#define IDC_FORMAT_WM                   4028
#define IDC_ICON_IPOD                   4029
#define IDC_FORMAT_CUSTOM               4029
#define IDC_FORMAT_IPOD                 4030
#define IDC_ICON_FLASH                  4031
#define IDC_FORMAT_FLASH                4032
#define IDC_EDIT_USERNAME               4033
#define IDC_EDT_KEY                     4033
#define IDC_KEYWORDS_EDIT_TITLE         4033
#define IDS_STRUCTEDITOR_DELETE_DISABLED 4034
#define IDC_EDIT_PASSWORD               4034
#define IDS_SG_WRITE_ERROR              4035
#define IDC_EDIT_YOUTUBE                4036
#define IDC_EDIT_DESCRIPTION            4036
#define IDC_EDIT_KEYWORDS               4037
#define IDC_EDIT_SLIDESTAR              4038
#define IDC_COMBO_CATEGORY              4038
#define IDC_FORMAT_YOUTUBE              4039
#define IDC_FORMAT_SLIDESTAR            4040
#define IDC_EDIT_CUSTOM                 4041
#define IDC_EDIT_MC_SLIDES_NO           4042
#define IDC_CUSTOM_TITLE                4044
#define IDC_DEFAULT_TITLE               4045
#define IDC_COMBO_CUSTOM                4047
#define IDC_PROFILE_MANAGER             4048
#define IDB_FLASH                       4049
#define IDB_IPOD                        4050
#define IDC_USERNAME                    4052
#define IDC_PASSWORD                    4053
#define IDC_TITLE_YT                    4054
#define IDC_DESCRIPTION                 4055
#define IDC_KEYWORDS                    4056
#define IDC_CATEGORY                    4057
#define IDC_PRIVACY                     4058
#define IDC_CHECK_PRIVACY               4059
#define IDC_HOSTNAME                    4060
#define IDC_EDIT_HOSTNAME               4061
#define IDC_EDIT_YT_TITLE               4062
#define IDC_EDIT_YT_KEYWORDS            4063
#define IDC_LBL_YT_TITLE                4064
#define IDC_LBL_YT_KEYWORDS             4065
#define IDC_TYDLG_SEPARATOR             4066
#define IDC_STD_INDEX                   4067
#define IDC_STD_INDEX_ALWAYS            4068
#define IDC_STC_DIRECT_LIVECONTEXT      4069
#define IDC_PROGRESS                    4071
#define IDC_STATUS                      4072
#define IDI_CLICK_ICON_LS               4073
#define IDC_STC_KEY_GROUP               4074
#define IDC_KEYWORDS_STATIC_GROUP       4075
#define IDC_KEYWORDS_EDIT_KEYWORDS      4076
#define IDC_KEYWORDS_STATIC_TITLE       4077
#define IDC_KEYWORDS_STATIC_KEYWORDS    4078
#define IDS_KEYWORDS_DIALOG_TITLE       4079
#define IDC_GROUPBOX                    4080
#define IDC_CLICKPAGES_GROUPBOX         4080
#define IDC_STRUCTURE_VIEW              4081
#define IDC_STC_ENTER_LICENSE_TEXT      4082
#define IDS_NO_ADMIN                    4083
#define IDC_CHECK_MC_SHOW_FOOTER        4084
#define IDC_CHECK_MC_SHOW_TABLE_OF_CONTENT 4085
#define IDC_SPIN_MC_SLIDES_NO           4086
#define IDC_CHECK_MC_SHOW_HEADER        4087
#define IDC_STATIC_MC_SLIDES_NO         4088
#define IDC_CHECK_MC_SHOW_COVER_SHEET   4089
#define IDC_PAGE_REMOVE_BUTTON_ARRAY    8000
#define IDC_SPLASHSCREEN_IMAGE          8001
#define IDS_SPLASHSCREEN_VERSION        8002
#define IDB_YOUTUBE                     8002
#define IDS_SPLASHSCREEN_LANGUAGE       8003
#define IDB_SLIDESTAR                   8003
#define IDS_SPLASHSCREEN_LICENSE_ERROR  8004
#define IDS_SPLASHSCREEN_ERROR          8005
#define IDC_SPLASHSCREEN_STATE          8006
#define IDC_SPLASHSCREEN_EVAL           8007
#define IDS_SPLASHSCREEN_EVALEXPIRED    8008
#define IDS_SPLASHSCREEN_EVALDAYS       8009
#define IDS_SPLASHSCREEN_EXPIRED        8010
#define IDS_SPLASHSCREEN_EXPIRATION     8011
#define IDS_SPLASHSCREEN_INTERNALRELEASE 8012
#define IDC_SPLASHSCREEN_VERSION        8013
#define IDS_SPLASHSCREEN_ALLRIGHTSRESERVED 8014
#define IDS_SPLASHSCREEN_STATE          8015
#define IDS_ERR_TOOLKIT_LANG_FILE_MISSING 8016
#define IDC_SPLASHSCREEN_PROGRESS       8018
#define IDS_FORMAT_FLASH                8019
#define IDS_FORMAT_WM                   8020
#define IDS_FORMAT_RM                   8021
#define IDS_FORMAT_IPOD                 8022
#define IDS_FORMAT_LPD                  8023
#define IDS_FORMAT_YOUTUBE              8024
#define IDS_FORMAT_SLIDESTAR            8025
#define IDS_PUBLISHING_WINDOW_TITLE     8026
#define IDS_FORMAT_CUSTOM               8027
#define IDB_CUSTOM                      8031
#define IDB_CLIX                        8032
#define IDD_YOUTUBE_SETTINGS            8033
#define IDD_SLIDESTAR_SETTINGS          8034
#define IDD_DLG_DIRECT_LIVECONTEXT      8035
#define IDD_DLG_ENTER_LICENSE           8035
#define IDD_LIVECONTEXT_STARTSCREEN     8036
#define IDB_BM_SHIELD                   8037
#define IDD_DIALOG_KEYWORDS             8038
#define IDB_CLICK_ICON                  8039
#define ID_PROFILE_FLASH                23523
#define ID_PROFILE_RM                   23524
#define ID_PROFILE_WM                   23525
#define ID_PROFILE_IPOD                 23526
#define ID_PROFILE_OTHER                23527
#define ID_PROFILE_LPD                  23528
#define ID_PROFILE_YOUTUBE              23529
#define ID_PROFILE_SLIDESTAR            23530
#define ID_PROFILE_CLIX                 23531
#define ID_PROFILE_CUSTOM               23532
#define IDS_YTTS_TOO_LONG               23540
#define IDS_YTTS_TOO_SHORT              23541
#define IDS_YTTS_ILLEGAL_CHARACTERS     23542
#define IDS_YTTS_TITLE                  23543
#define IDS_YTTS_DESCRIPTION            23544
#define IDS_YTTS_KEYWORD                23545
#define IDS_YTTS_KEYWORD_NUMBER         23546
#define IDS_YTTS_TITLE_CHARS            23547
#define IDS_YTTS_EMPTY                  23548
#define IDS_YT_CAT_AUTOS                23551
#define IDS_YT_CAT_COMEDY               23552
#define IDS_YT_CAT_EDUCATION            23553
#define IDS_YT_CAT_ENTERTAINTMENT       23554
#define IDS_YT_CAT_FILM                 23555
#define IDS_YT_CAT_GAMES                23556
#define IDS_YT_CAT_HOWTO                23557
#define IDS_YT_CAT_MUSIC                23558
#define IDS_YT_CAT_NEWS                 23559
#define IDS_YT_CAT_NONPROFIT            23560
#define IDS_YT_CAT_PEOPLE               23561
#define IDS_YT_CAT_ANIMALS              23562
#define IDS_YT_CAT_TECH                 23563
#define IDS_YT_CAT_SPORTS               23564
#define IDS_YT_CAT_TRAVEL               23565
#define IDS_LC_RECORD_MODE              23566
#define IDS_LC_EDIT_MODE                23567
#define IDS_LC_PREVIEW_MODE             23568
#define IDC_PROGRESS_BAR                42222
#define IDC_PROGRESS_LABEL              42223

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        8040
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         4090
#define _APS_NEXT_SYMED_VALUE           4017
#endif
#endif
