//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Publisher.rc
//
#define IDR_MANIFEST                    1
#undef RT_MANIFEST
#define RT_MANIFEST                     24
#define IDD_ABOUTBOX                    100
#define IDD_PUBLISHER_FORM              101
#define IDD_LRDINFO_FORM                101
#define IDR_MAINFRAME                   128
#define IDR_PROFILTYPE                  129
#define IDD_SETTINGS_TARGET             130
#define IDD_SETTINGS_MESSAGE            131
#define IDD_SETTINGS_FORM               132
#define IDD_SETTINGS_TEMPLATE           133
#define IDD_SETTINGS_SCORM              134
#define IDD_SETTINGS_SLIDES             135
#define IDD_SETTINGS_DIALOGTEMPLATE     136
#define IDD_SETTINGS_LPD                137
#define IDD_SETTINGS_VIDEOCLIPS         139
#define IDD_SETTINGS_WM                 140
#define IDD_SETTINGS_MEDIA_WM           140
#define IDD_SETTINGS_RM                 142
#define IDD_SETTINGS_MEDIA_RM           142
#define IDD_SETTINGS_TRANSFER           145
#define IDD_SETTINGS_MEDIA              148
#define IDB_FRONTPAGE                   150
#define IDD_FRONTPAGE                   151
#define IDD_SETTINGS_URLS               153
#define IDD_PROFILE_VIEW                154
#define IDD_PUBLISH_PROGRESS            156
#define IDC_LRDINFO_FILENAME            1003
#define IDC_LRDINFO_RECORDDATE          1004
#define IDC_LRDINFO_TITLE               1005
#define IDC_LRDINFO_AUTHOR              1006
#define IDC_LRDINFO_PRODUCER            1007
#define IDC_LRDINFO_KEYWORDS            1008
#define IDC_LRDINFO_VIDEO               1009
#define IDC_LRDINFO_CLIPSLIST           1010
#define IDC_TARGET_LECTURNITY           1011
#define IDC_LRDINFO_AUDIO               1011
#define IDC_TARGET_STREAMING            1012
#define IDC_TARGET_FLASH                1013
#define IDC_TARGET_MEDIA_WMT            1014
#define IDC_TARGET_MEDIA_RM             1015
#define IDC_SETTINGS_MESSAGE            1015
#define IDC_MESSAGE_ICON                1016
#define IDC_SETTINGS_PROFILE            1017
#define IDC_SETTINGS_TAB                1018
#define IDC_SETTINGS_SCORM              1019
#define IDC_SETTINGS_SCORMSTRICT        1020
#define IDC_TEMPLATE_TITLE              1021
#define IDC_TEMPLATE_SCORM              1022
#define IDC_TEMPLATE_CONFIGURE          1023
#define IDC_SCORM_CONFIGURE             1024
#define IDC_LPD_AUDIO_WAV               1025
#define IDC_LPD_AUDIO_AQS               1026
#define IDC_CHECK1                      1027
#define IDC_CHECK2                      1028
#define IDC_CHECK3                      1029
#define IDC_CHECK4                      1030
#define IDC_CHECK5                      1031
#define IDC_VIDEO_SIZE_STANDARD         1032
#define IDC_VIDEO_SIZE_MAXCLIP          1033
#define IDC_SLIDES_SIZE_SCREEN          1034
#define IDC_SLIDES_SIZE_SELECT          1035
#define IDC_VIDEO_SIZE_CUSTOM           1035
#define IDC_SLIDES_SIZE_CUSTOM          1036
#define IDC_VIDEO_SIZE_WIDTH            1037
#define IDC_VIDEO_SIZE_HEIGHT           1038
#define IDC_SLIDES_POINTER              1039
#define IDC_VIDEO_SIZE_WIDTH2           1039
#define IDC_SLIDES_DYNAMIC              1040
#define IDC_VIDEO_SIZE_HEIGHT2          1040
#define IDC_SLIDES_COMPRESSION          1041
#define IDC_SLIDES_SIZE_STANDARD        1042
#define IDC_SLIDES_SIZE_ORIGINAL        1043
#define IDC_SLIDES_SIZE_WIDTH           1044
#define IDC_SLIDES_SIZE_HEIGHT          1045
#define IDC_SLIDES_SIZE_KEEPASPECT      1046
#define IDC_VIDEO_SPLITCLIPS            1047
#define IDC_VIDEO_SIZE_KEEPASPECT       1048
#define IDC_RADIO4                      1049
#define IDC_RADIO5                      1050
#define IDC_VIDEO_SIZE_KEEPASPECT2      1051
#define IDC_RADIO6                      1052
#define IDC_RADIO1                      1053
#define IDC_RADIO2                      1054
#define IDC_RADIO3                      1055
#define IDC_WM_TARGETBITRATE            1056
#define IDC_EDIT1                       1057
#define IDC_EDIT2                       1058
#define IDC_EDIT3                       1059
#define IDC_BUTTON1                     1060
#define IDC_CHECK6                      1061
#define IDC_TRANSFER_TARGET1            1061
#define IDC_CHECK7                      1062
#define IDC_TRANSFER_CONFIGURE1         1062
#define IDC_CHECK8                      1063
#define IDC_TRANSFER_TYPE2              1063
#define IDC_CHECK9                      1064
#define IDC_TRANSFER_TARGET2            1064
#define IDC_RM_VIDEOQUALITY_SELECT      1065
#define IDC_TRANSFER_CONFIGURE2         1065
#define IDC_TRANSFER_TYPE0              1069
#define IDC_TRANSFER_TYPE1              1070
#define IDC_TRANSFER_TARGET0            1071
#define IDC_TRANSFER_CONFIGURE0         1072
#define IDC_START_PUBLISHING            1073
#define IDC_SETTINGS_TARGETFORMAT       1074
#define IDC_MEDIA_FORMAT                1075
#define IDC_COMBO1                      1076
#define IDC_FRONTPAGE_PROFILE           1076
#define IDC_TRANSFER_SERVERTYPE         1076
#define IDC_PROFILE_SELECT              1076
#define IDC_FRONTPAGE_BROWSE            1079
#define IDC_FRONTPAGE_EXPERTMODE        1080
#define IDC_FRONTPAGE_FILENAME          1081
#define IDC_FRONTPAGE_DONTSHOWAGAIN     1082
#define IDC_TRANSFER_MEDIAGROUP         1083
#define IDC_TRANSFER_MEDIA_LB_TRANSFER  1084
#define IDC_TRANSFER_MEDIA_LB_TARGET    1085
#define IDC_TRANSFER_LB_SERVERTYPE      1086
#define IDC_TRANSFER_SERVERURL          1087
#define IDC_TRANSFER_LB_SERVERURL       1088
#define IDC_TRANSFER_LB_SUBDIR          1089
#define IDC_TRANSFER_SUBDIR_GROUP       1090
#define IDC_TRANSFER_LB_SUBDIR_AUTO     1091
#define IDC_TRANSFER_LB_SUBDIR_MANUAL   1092
#define IDC_PROFILE_STARTPUBLISH        1093
#define IDC_LRDINFO_CAPTION             1095
#define IDC_SETTINGS_CAPTION            1096
#define IDC_PROFILE_CAPTION             1097
#define IDC_PROGRESS_TOTAL              1098
#define IDC_PROGRESS_DETAIL             1099
#define IDC_LB_DETAIL                   1100
#define IDC_CANCEL_PUBLISH              1101
#define IDC_LB_TIMELEFT                 1102
#define ID_FILE_OPEN_LRD                32773
#define ID__IMCAGWEBAUFTRITT            32774
#define ID__HILFE                       32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1103
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
