TOPDIR = ../../../../..
LOCALDIR = imc/lecturnity/util/net/ftp

SUBDIRS =

CLASSES = FTPClient.class FTPControlSocket.class \
	FTPConnectMode.class FTPDataSocket.class \
	FTPTransferType.class FTPException.class

include ../../Makefile.inc
