all: doc


doc: 
	javadoc -d ../doc imc.epresenter.filesdk \
	imc.epresenter.filesdk.util \
	imc.epresenter.media.protocol.epf \
	imc.epresenter.converter \
	imc.epresenter.player \
	imc.epresenter.player.audio \
	imc.epresenter.player.event \
	imc.epresenter.player.master \
	imc.epresenter.player.net \
	imc.epresenter.player.util \
	imc.epresenter.player.whiteboard \
	imc.lecturnity.util \
	imc.lecturnity.util.wizards \
	imc.lecturnity.util.ui \
	imc.lecturnity.converter \
	imc.lecturnity.converter.wizard

