# Makefile 29.10.01

TOPDIR = ../../..
LOCALDIR = imc/epresenter/converter

SUBDIRS = 
CLASSES = PresentationConverter.class \
          DefaultConversionDisplay.class ConversionDisplay.class

include Makefile.inc
