/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imc_lecturnity_converter_LPLibs */

#ifndef _Included_imc_lecturnity_converter_LPLibs
#define _Included_imc_lecturnity_converter_LPLibs
#ifdef __cplusplus
extern "C" {
#endif
#undef imc_lecturnity_converter_LPLibs_WARN_GLYPH_NOT_FOUND
#define imc_lecturnity_converter_LPLibs_WARN_GLYPH_NOT_FOUND 16L
#undef imc_lecturnity_converter_LPLibs_WARN_PAGE_TOO_SHORT
#define imc_lecturnity_converter_LPLibs_WARN_PAGE_TOO_SHORT 8L
#undef imc_lecturnity_converter_LPLibs_WARN_FONTSTYLES_IN_TTF
#define imc_lecturnity_converter_LPLibs_WARN_FONTSTYLES_IN_TTF 4L
#undef imc_lecturnity_converter_LPLibs_WARN_STOPMARK_LOSS
#define imc_lecturnity_converter_LPLibs_WARN_STOPMARK_LOSS 2L
#undef imc_lecturnity_converter_LPLibs_WARN_FONT_NOT_FOUND
#define imc_lecturnity_converter_LPLibs_WARN_FONT_NOT_FOUND 1L
#undef imc_lecturnity_converter_LPLibs_SUCCESS
#define imc_lecturnity_converter_LPLibs_SUCCESS 0L
#undef imc_lecturnity_converter_LPLibs_UNSPECIFIC_ERROR
#define imc_lecturnity_converter_LPLibs_UNSPECIFIC_ERROR -1L
#undef imc_lecturnity_converter_LPLibs_INPUT_FILE_MISSING
#define imc_lecturnity_converter_LPLibs_INPUT_FILE_MISSING -2L
#undef imc_lecturnity_converter_LPLibs_EMBED_FILE_MISSING
#define imc_lecturnity_converter_LPLibs_EMBED_FILE_MISSING -3L
#undef imc_lecturnity_converter_LPLibs_OPEN_FILE_ERROR
#define imc_lecturnity_converter_LPLibs_OPEN_FILE_ERROR -4L
#undef imc_lecturnity_converter_LPLibs_WHITEBOARD_CORRUPT
#define imc_lecturnity_converter_LPLibs_WHITEBOARD_CORRUPT -5L
#undef imc_lecturnity_converter_LPLibs_COMMAND_START_FAILED
#define imc_lecturnity_converter_LPLibs_COMMAND_START_FAILED -6L
#undef imc_lecturnity_converter_LPLibs_COMMAND_EXECUTION_FAILED
#define imc_lecturnity_converter_LPLibs_COMMAND_EXECUTION_FAILED -7L
#undef imc_lecturnity_converter_LPLibs_AUDIO_CONVERSION_FAILED
#define imc_lecturnity_converter_LPLibs_AUDIO_CONVERSION_FAILED -8L
#undef imc_lecturnity_converter_LPLibs_FONT_CONVERSION_FAILED
#define imc_lecturnity_converter_LPLibs_FONT_CONVERSION_FAILED -9L
#undef imc_lecturnity_converter_LPLibs_IMAGE_CONVERSION_FAILED
#define imc_lecturnity_converter_LPLibs_IMAGE_CONVERSION_FAILED -10L
#undef imc_lecturnity_converter_LPLibs_DOCUMENT_TOO_COMPLEX
#define imc_lecturnity_converter_LPLibs_DOCUMENT_TOO_COMPLEX -11L
#undef imc_lecturnity_converter_LPLibs_VIDEO_FILTERS_MISSING
#define imc_lecturnity_converter_LPLibs_VIDEO_FILTERS_MISSING -12L
#undef imc_lecturnity_converter_LPLibs_VIDEO_DECODING_FAILED
#define imc_lecturnity_converter_LPLibs_VIDEO_DECODING_FAILED -13L
#undef imc_lecturnity_converter_LPLibs_VIDEO_CONVERSION_FAILED
#define imc_lecturnity_converter_LPLibs_VIDEO_CONVERSION_FAILED -14L
#undef imc_lecturnity_converter_LPLibs_CLIP_CONVERSION_FAILED
#define imc_lecturnity_converter_LPLibs_CLIP_CONVERSION_FAILED -15L
#undef imc_lecturnity_converter_LPLibs_PAGE_TOO_SHORT
#define imc_lecturnity_converter_LPLibs_PAGE_TOO_SHORT -16L
#undef imc_lecturnity_converter_LPLibs_AUDIO_8_16_KHZ_NOT_SUPPORTED
#define imc_lecturnity_converter_LPLibs_AUDIO_8_16_KHZ_NOT_SUPPORTED -17L
#undef imc_lecturnity_converter_LPLibs_FLV_NO_OVERWRITE
#define imc_lecturnity_converter_LPLibs_FLV_NO_OVERWRITE -18L
#undef imc_lecturnity_converter_LPLibs_TOO_MANY_OPEN_FILES
#define imc_lecturnity_converter_LPLibs_TOO_MANY_OPEN_FILES -19L
#undef imc_lecturnity_converter_LPLibs_INTERACTIVE_PAGE_TOO_SHORT
#define imc_lecturnity_converter_LPLibs_INTERACTIVE_PAGE_TOO_SHORT -20L
#undef imc_lecturnity_converter_LPLibs_NO_MEMORY
#define imc_lecturnity_converter_LPLibs_NO_MEMORY -21L
#undef imc_lecturnity_converter_LPLibs_NO_SWF_CREATED
#define imc_lecturnity_converter_LPLibs_NO_SWF_CREATED -22L
#undef imc_lecturnity_converter_LPLibs_NOT_ENOUGH_DISK_SPACE
#define imc_lecturnity_converter_LPLibs_NOT_ENOUGH_DISK_SPACE -23L
#undef imc_lecturnity_converter_LPLibs_CANCELLED
#define imc_lecturnity_converter_LPLibs_CANCELLED -99L
#undef imc_lecturnity_converter_LPLibs_FLASH_FORMAT_NORMAL
#define imc_lecturnity_converter_LPLibs_FLASH_FORMAT_NORMAL 0L
#undef imc_lecturnity_converter_LPLibs_FLASH_FORMAT_SLIDESTAR
#define imc_lecturnity_converter_LPLibs_FLASH_FORMAT_SLIDESTAR 1L
#undef imc_lecturnity_converter_LPLibs_FLASH_FORMAT_PSP
#define imc_lecturnity_converter_LPLibs_FLASH_FORMAT_PSP 2L
#undef imc_lecturnity_converter_LPLibs_FLASH_FORMAT_FLEX
#define imc_lecturnity_converter_LPLibs_FLASH_FORMAT_FLEX 3L
#undef imc_lecturnity_converter_LPLibs_PSP_STANDARD_WIDTH
#define imc_lecturnity_converter_LPLibs_PSP_STANDARD_WIDTH 480L
#undef imc_lecturnity_converter_LPLibs_PSP_STANDARD_HEIGHT
#define imc_lecturnity_converter_LPLibs_PSP_STANDARD_HEIGHT 272L
#undef imc_lecturnity_converter_LPLibs_PSP_CONTENT_WIDTH
#define imc_lecturnity_converter_LPLibs_PSP_CONTENT_WIDTH 363L
#undef imc_lecturnity_converter_LPLibs_PSP_CONTENT_HEIGHT
#define imc_lecturnity_converter_LPLibs_PSP_CONTENT_HEIGHT 272L
#undef imc_lecturnity_converter_LPLibs_TELEPOINTER_TYPE_POINTER
#define imc_lecturnity_converter_LPLibs_TELEPOINTER_TYPE_POINTER 0L
#undef imc_lecturnity_converter_LPLibs_TELEPOINTER_TYPE_CURSOR
#define imc_lecturnity_converter_LPLibs_TELEPOINTER_TYPE_CURSOR 1L
#undef imc_lecturnity_converter_LPLibs_NUMBER_OF_NAVIGATION_STATES
#define imc_lecturnity_converter_LPLibs_NUMBER_OF_NAVIGATION_STATES 8L
/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_init
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    cleanUp
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_cleanUp
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    getListOfInteractiveOpenedFiles
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_imc_lecturnity_converter_LPLibs_getListOfInteractiveOpenedFiles
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    lpdPrepareCopiesOfInteractiveOpenedFiles
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_lpdPrepareCopiesOfInteractiveOpenedFiles
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    scormInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_scormInit
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    scormCleanUp
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_scormCleanUp
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    scormGetSettings
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_converter_LPLibs_scormGetSettings
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    scormUseSettings
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_scormUseSettings
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    scormConfigure
 * Signature: (Ljava/awt/Window;Z)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_scormConfigure
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    scormSetTargetFileName
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_scormSetTargetFileName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    scormGetTargetFilePath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_converter_LPLibs_scormGetTargetFilePath
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    scormSetIndexFileName
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_scormSetIndexFileName
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    scormAddResourceFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_scormAddResourceFile
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    scormAddMetadataKeyword
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_scormAddMetadataKeyword
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    scormAddGeneralKeyword
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_scormAddGeneralKeyword
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    scormAddFullTextString
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_scormAddFullTextString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    scormCreatePackage
 * Signature: (Ljava/awt/Window;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_scormCreatePackage
  (JNIEnv *, jclass, jobject);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    scormGetProgress
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_scormGetProgress
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    scormCancel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_scormCancel
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    scormGetLanguage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_converter_LPLibs_scormGetLanguage
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    scormGetVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_converter_LPLibs_scormGetVersion
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    scormGetStatus
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_converter_LPLibs_scormGetStatus
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    scormGetFullTextAsKeywords
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imc_lecturnity_converter_LPLibs_scormGetFullTextAsKeywords
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    templateInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_templateInit
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    templateCleanUp
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_templateCleanUp
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    templateReadSettings
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_templateReadSettings
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    templateReadSettingsFromFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_templateReadSettingsFromFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    templateUseSettings
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_templateUseSettings
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    templateGetSettings
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_converter_LPLibs_templateGetSettings
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    templateGetActivePath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_converter_LPLibs_templateGetActivePath
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    templateConfigure
 * Signature: (Ljava/awt/Window;Z)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_templateConfigure
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    templateAddKeyword
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_templateAddKeyword
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    templateGetTitle
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_converter_LPLibs_templateGetTitle
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    templateGetDescription
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_converter_LPLibs_templateGetDescription
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    templateGetAuthor
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_converter_LPLibs_templateGetAuthor
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    templateGetCopyright
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_converter_LPLibs_templateGetCopyright
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    templateIsScormCompliant
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imc_lecturnity_converter_LPLibs_templateIsScormCompliant
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    templateIsUtfTemplate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imc_lecturnity_converter_LPLibs_templateIsUtfTemplate
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    templateDoParse
 * Signature: (Ljava/awt/Window;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_templateDoParse
  (JNIEnv *, jclass, jobject);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    templateSetTargetDirectory
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_templateSetTargetDirectory
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    templateGetTargetDirectory
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_converter_LPLibs_templateGetTargetDirectory
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    templateGetFileCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_templateGetFileCount
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    templateGetFile
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_converter_LPLibs_templateGetFile
  (JNIEnv *, jclass, jint);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    templateGetIndexFile
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_converter_LPLibs_templateGetIndexFile
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    templateSetDocumentType
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_templateSetDocumentType
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    templateSetScormEnabled
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_templateSetScormEnabled
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashSetScormEnabled
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashSetScormEnabled
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    templateSetTargetFormat
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_templateSetTargetFormat
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    templateGetMaxSlidesWidth
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_templateGetMaxSlidesWidth
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    templateGetMaxSlidesHeight
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_templateGetMaxSlidesHeight
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    templateGetGlobalSetting
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_converter_LPLibs_templateGetGlobalSetting
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    templateGetStandardNavigationStates
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_imc_lecturnity_converter_LPLibs_templateGetStandardNavigationStates
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    templatePutStandardNavigationStatesToLrd
 * Signature: (Ljava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_templatePutStandardNavigationStatesToLrd
  (JNIEnv *, jclass, jstring, jintArray);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashSetInputFiles
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashSetInputFiles
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashSetInputAudioIsFromFlv
 * Signature: (ZLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashSetInputAudioIsFromFlv
  (JNIEnv *, jclass, jboolean, jstring);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashSetInputVideoFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;IIZ)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashSetInputVideoFile
  (JNIEnv *, jclass, jstring, jstring, jint, jint, jboolean);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashSetNumberOfClips
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashSetNumberOfClips
  (JNIEnv *, jclass, jint);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashSetInputClipFile
 * Signature: (ILjava/lang/String;Ljava/lang/String;IIZJJ)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashSetInputClipFile
  (JNIEnv *, jclass, jint, jstring, jstring, jint, jint, jboolean, jlong, jlong);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashSetInputStillImageFile
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashSetInputStillImageFile
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashSetOutputFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashSetOutputFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashSetRtmpPath
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashSetRtmpPath
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashSetWbInputDimension
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashSetWbInputDimension
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashSetWbOutputDimension
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashSetWbOutputDimension
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashSetMovieDimension
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashSetMovieDimension
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashSetFlashVersion
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashSetFlashVersion
  (JNIEnv *, jclass, jint);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashSetAutostartMode
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashSetAutostartMode
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashSetSgStandAloneMode
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashSetSgStandAloneMode
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashSetDrawEvalNote
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashSetDrawEvalNote
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashSetPspDesign
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashSetPspDesign
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashSetShowClipsInVideoArea
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashSetShowClipsInVideoArea
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashHideLecturnityIdentity
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashHideLecturnityIdentity
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashEnableOutputDir
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashEnableOutputDir
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashResetAllDimensions
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashResetAllDimensions
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashGetOutputWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashGetOutputWidth
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashGetOutputHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashGetOutputHeight
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashGetContentDimensions
 * Signature: (Ljava/awt/Dimension;Ljava/awt/Dimension;Ljava/awt/Dimension;Ljava/awt/Dimension;ZZZLjava/awt/Dimension;Ljava/awt/Dimension;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashGetContentDimensions
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jboolean, jboolean, jboolean, jobject, jobject);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashObtainMovieInsets
 * Signature: (Ljava/awt/Insets;Ljava/awt/Dimension;ZLjava/awt/Dimension;Ljava/awt/Dimension;Z)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashObtainMovieInsets
  (JNIEnv *, jclass, jobject, jobject, jboolean, jobject, jobject, jboolean);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashConvertImages
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashConvertImages
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashConvertFonts
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashConvertFonts
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashConvertAudioToMp3
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashConvertAudioToMp3
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashSetStandardNavigationStates
 * Signature: (IIIIII)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashSetStandardNavigationStates
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashBuildMovie
 * Signature: (IILjava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;IZ)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashBuildMovie
  (JNIEnv *, jclass, jint, jint, jstring, jstring, jint, jstring, jstring, jint, jboolean);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashCreateSlidestar
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashCreateSlidestar
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashCreateFlexFiles
 * Signature: (Ljava/lang/String;Ljava/lang/String;ZZZZZZ)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashCreateFlexFiles
  (JNIEnv *, jclass, jstring, jstring, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashPrepareScorm
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashPrepareScorm
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashCancel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashCancel
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashCleanup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashCleanup
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashLastErrorDetail
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_converter_LPLibs_flashLastErrorDetail
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashGetFontListFontNotFound
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_converter_LPLibs_flashGetFontListFontNotFound
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashGetFontListGlyphNotFound
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_converter_LPLibs_flashGetFontListGlyphNotFound
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashGetFontListStylesNotSupported
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_converter_LPLibs_flashGetFontListStylesNotSupported
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashGetPreloaderFilename
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_converter_LPLibs_flashGetPreloaderFilename
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashGetTooShortPagesTimes
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_converter_LPLibs_flashGetTooShortPagesTimes
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flashShowColorDialog
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flashShowColorDialog
  (JNIEnv *, jclass, jint);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    videoPrepare
 * Signature: (Ljava/lang/String;Ljava/lang/String;IIIIIZZZ)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_videoPrepare
  (JNIEnv *, jclass, jstring, jstring, jint, jint, jint, jint, jint, jboolean, jboolean, jboolean);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    videoConvertStart
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_videoConvertStart
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    videoConvertCancel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_videoConvertCancel
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    videoGetProgress
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_videoGetProgress
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    videoCleanup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_videoCleanup
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flvPrepare
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;IIIIZZZZ)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flvPrepare
  (JNIEnv *, jclass, jstring, jint, jstring, jstring, jint, jint, jint, jint, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flvAddClip
 * Signature: (Ljava/lang/String;IZ)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flvAddClip
  (JNIEnv *, jclass, jstring, jint, jboolean);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flvConvertStart
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flvConvertStart
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flvConvertCancel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flvConvertCancel
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flvCheckOverwrite
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_imc_lecturnity_converter_LPLibs_flvCheckOverwrite
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flvGetProgress
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flvGetProgress
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_converter_LPLibs
 * Method:    flvCleanup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_converter_LPLibs_flvCleanup
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
