//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LPLibs.rc
//
#define IDR_MANIFEST                    1
#define IDS_SD_YOUTUBE                  3
#define IDS_LANGUAGE                    11
#define TPERR_FILE_NOT_FOUND            12
#define TPERR_SECTION_NOT_FOUND         13
#define TPERR_EVAL_ERROR                14
#define TPERR_COPY_FAILED               15
#define TPERR_READ_TEMPLATE             16
#define TPERR_WRITE_TEMPLATE            17
#define TPERR_CREATE_DIR                18
#define TPERR_READ_FILES                19
#define TP_UNDEFINED                    20
#define IDS_TMP_TEMPLATE_CHANGED        21
#define IDS_TMP_IMAGE_MISMATCH          22
#define IDS_TMP_CONFIG_FILEFILTER       23
#define IDS_TMP_CONFIG_NOTVALID         24
#define TPERR_IMAGE_NOT_FOUND           25
#define IDS_TMP_NOTEMPLATE              26
#define TPERR_NO_TEMP_DIR               27
#define IDS_IMAGE_FILEFILTER            28
#define IDS_TEMPLATE_VAR_RESETCONFIRM   29
#define IDS_TEMPLATE_VAR_RESETNOTIFY    30
#define IDS_COMPATIBLE                  31
#define IDS_NOT_COMPATIBLE              32
#define IDS_FLASH_PRELOAD               33
#define IDS_FLASH_SLIDE                 34
#define IDS_FLASH_OF                    35
#define IDS_WEBPAGE_LECTURNITY          36
#define IDS_VERSION                     37
#define IDS_SAVE_TEMPLATE_FOR_ALL       38
#define IDS_LOAD_DEFAULT_CONFIG         39
#define IDS_FLV_NOT_FOUND_ERROR         40
#define IDS_ERROR                       41
#define IDS_WARNING                     42
#define IDS_SERVER_ERROR                43
#define IDS_FLV_STREAMING_ERROR         44
#define IDS_FLASH_PRELOAD_SLIDESTAR     45
#define IDS_STRING36                    46
#define IDS_CONFIRM_DELETE_CAPTION      46
#define IDS_CONFIRM_DELETE_TEXT         47
#define IDS_PPR_FILEFILTER              48
#define IDS_EXPORT_LPD                  50
#define IDS_EXPORT_WM                   51
#define IDS_EXPORT_REAL                 52
#define IDS_EXPORT_FLASH                53
#define IDS_EXPORT_IPOD                 54
#define IDS_SD_SLIDESTAR                60
#define IDS_SD_PODCAST                  61
#define IDS_SD_WEBSERVER                62
#define IDS_SD_LOCAL                    63
#define IDS_SD_WEBSERVER_FT             64
#define IDS_SD_WEB_STREAMING            65
#define IDS_SD_WEB_STREAMING_FT         66
#define IDS_SD_FILE_SERVER              67
#define IDS_ERROR_ACTION_NEW            68
#define IDS_ERROR_ACTION_EDIT           69
#define IDS_ERROR_ACTION_IMPORT         70
#define IDS_ERROR_ACTION_ACCESS         71
#define IDS_ERROR_GETACTIVEPROFILE      72
#define IDS_ERROR_JNI_NEW               73
#define IDS_ERROR_APPLICATIONDIR        74
#define IDS_ERROR_CREATESUBDIR          75
#define IDS_ERROR_PERMISSION            76
#define IDS_ERROR_JNI_INSERT_NEW        77
#define IDS_ERROR_JNI_EDIT              78
#define IDS_ERROR_NOTINLIST_EDIT        79
#define IDS_ERROR_JNI_INSERT_EDIT       80
#define IDS_ERROR_DELETE_FILE           81
#define IDS_ERROR_FILENOTFOUND_IMPORT   82
#define IDS_ERROR_PERMISSION_READ_IMPORT 83
#define IDS_ERROR_READ_IMPORT           84
#define IDS_ERROR_FORMAT_IMPORT         85
#define IDS_ERROR_CREATESUBDIR_EXPORT   86
#define IDS_ERROR_PERMISSION_EXPORT     87
#define IDS_ERROR_WRITE_EXPORT          88
#define IDS_ERROR_JNI_MAINWINDOW        89
#define IDS_ERROR_READ_ACTIVEPROFILE    90
#define IDS_ERROR_WRITE_ACTIVEPROFILE   91
#define IDS_ERROR_WRITE                 92
#define IDS_ERROR_ACTION_RENAME         93
#define IDS_ERROR_NO_LRD                94
#define IDS_CAPTION_NO_LRD              95
#define IDS_ERROR_NOADMIN               96
#define IDS_CAPTION_NOPERMISSION        97
#define IDS_ERROR_EDIT_NOLRD            98
#define IDD_SCORM_GENERAL               102
#define IDD_SCORM_RIGHTS                103
#define IDD_SCORM_CATALOGENTRY          104
#define IDD_TEMPLATE_SELECT             106
#define IDD_TEMPLATE_VARIABLES          107
#define IDD_TEMPLATE_VAR_INT            108
#define IDD_TEMPLATE_DLG                108
#define IDD_TEMPLATE_VAR_TEXT           109
#define IDS_DEFAULT_NAME                109
#define IDD_TEMPLATE_VAR_TEMPLATE       110
#define IDD_TEMPLATE_VAR_COLOR          111
#define IDD_TEMPLATE_VAR_GENERAL        112
#define IDD_TEMPLATE_VAR_NONE           113
#define IDD_SCORM_PROGRESS              114
#define IDD_TRANSFER_CONFIGURE          115
#define IDD_TEMPLATE_VAR_IMAGE          116
#define IDD_PROFILE_LIST                117
#define IDD_PROFILE_MANAGER             117
#define IDS_PROFILE_NAME                200
#define IDC_SCORM_LANGUAGE              2000
#define IDR_XML_SCOMETADATA             2002
#define IDC_SCORM_VERSION               2002
#define IDR_XML_IMSMANIFEST             2003
#define IDC_SCORM_STATUS                2004
#define IDC_CHECK1                      2005
#define IDC_SCORM_COST                  2005
#define IDC_TRANSFER_CHK_PASSWORD       2005
#define IDC_CHECK2                      2006
#define IDC_SCORM_COPYRIGHT             2006
#define IDC_SCORM_FULLTEXTKEYWORDS      2007
#define IDC_SCORM_TOTAL_PROGRESS        2008
#define IDC_SCORM_FILE_PROGRESS         2009
#define IDC_SCORM_PRGLABEL              2010
#define IDC_LIST1                       2011
#define IDC_TMP_SELECT_TEMPLATES        2011
#define IDC_BUTTON1                     2012
#define IDC_TEMPLATE_VAR_RESETALL       2012
#define IDC_BUTTON2                     2013
#define IDC_TMP_SELECT_REMOVE           2013
#define IDC_TRANSFER_TARGETCOMBO        2014
#define IDC_TRANSFER_PORT               2015
#define IDC_TRANSFER_LOCAL              2016
#define IDC_TRANSFER_FTP                2017
#define IDC_TRANSFER_SCP                2018
#define IDC_TRANSFER_HTTP               2019
#define IDD_TEMPLATE_PREVIEW            2019
#define IDC_TRANSFER_USERNAME           2020
#define IDD_TEMPLATE_VAR_SELECT         2020
#define IDC_TRANSFER_PASSWORD           2021
#define IDD_SCORM_RIGHTS_               2021
#define IDD_SCORM_CLASSIFICATION        2021
#define IDC_TRANSFER_LBL_USERNAME       2022
#define IDC_TRANSFER_LBL_PASSWORD       2023
#define IDC_TRANSFER_LBL_TARGET         2024
#define IDC_TRANSFER_LBL_PORT           2025
#define IDD_FLASH_STOPPMARKS_LOST_DLG   2025
#define IDC_TRANSFER_LBL_TECHNIQUE      2026
#define IDC_EDIT1                       2027
#define IDC_EDIT2                       2028
#define IDC_TEMPLATE_VAR_TEXT           2029
#define IDC_TEMPLATE_VAR_HTML_TEXT      2030
#define IDC_TEMPLATE_VARIABLES          2031
#define IDC_SPIN1                       2032
#define IDC_TMP_VAR_INT_SPIN            2032
#define IDC_TEMPLATE_VAR_COLOR          2035
#define IDC_TEMPLATE_VAR_IMAGE_BROWSE   2036
#define IDC_TEMPLATE_VAR                2037
#define IDC_TEMPLATE_VAR_IMAGE_REMOVE   2037
#define IDC_TEMPLATE_VAR_IMAGE          2038
#define IDC_TEMPLATE_VAR_NOVARSELECTED  2039
#define IDC_SCORM_DOCINFO               2040
#define IDC_SCORM_LB_LANGUAGE           2041
#define IDI_ICON_PUBLISHER              2041
#define IDI_ICON_XP_ERROR               2042
#define IDC_SCORM_SETTINGS_GROUP        2043
#define IDI_ICON_XP_INFO                2043
#define IDC_SCORM_DESC_SETTINGS         2044
#define IDI_ICON_XP_QUESTION            2044
#define IDC_SCORM_LB_VERSION            2045
#define IDI_ICON_XP_WARNING             2045
#define IDC_SCORM_LB_STATUS             2046
#define IDC_SCORM_COPYRIGHT_GROUP       2047
#define IDC_TMP_VARS_DESC               2048
#define IDC_TMP_VARS_CONTENT_GROUP      2049
#define IDC_TMP_SELECT_GROUP            2050
#define IDC_TMP_SELECT_DESC             2051
#define IDC_TMP_SELECT_ADD              2052
#define IDC_TMP_SELECT_INFORMATION_GROUP 2053
#define IDC_TMP_SELECT_AUTHOR_LABEL     2054
#define IDC_TMP_SELECT_COPYRIGHT_LABEL  2055
#define IDC_TMP_SELECT_PATH_LABEL       2056
#define IDC_TMP_SELECT_DESCRIPTION_LABEL 2057
#define IDC_TMP_SELECT_AUTHOR           2058
#define IDC_TMP_SELECT_COPYRIGHT        2059
#define IDC_TMP_SELECT_PATH             2060
#define IDC_TMP_SELECT_DESCRIPTION      2061
#define IDC_TMP_VARS_GROUP              2062
#define IDC_TMP_VAR_VARIABLE_LABEL      2063
#define IDC_TMP_VAR_TYPE_LABEL          2064
#define IDC_TMP_VAR_CONTENT_LABEL       2065
#define IDC_TMP_VAR_COLOR_TYPE          2066
#define IDC_TMP_VAR_COLOR_VARNAME       2067
#define IDC_TMP_VAR_COLORBUTTON         2068
#define IDC_TMP_VAR_GENERAL_TYPE        2069
#define IDC_TMP_VAR_RESETBUTTON         2070
#define IDC_TMP_VAR_WARNING_RP8_LABEL   2071
#define IDC_TMP_VAR_IMAGE_TYPE          2072
#define IDC_TMP_VAR_INT_TYPE            2074
#define IDC_TMP_VAR_TEXT_TYPE           2076
#define IDC_TMP_VAR_VARNAME             2077
#define IDC_TMP_VAR_INT_VALUE           2078
#define IDC_TEMPLATE_PREVIEW_IMG        2080
#define IDC_TMP_SELECT_PREVIEW          2081
#define IDC_TEMPLATE_VAR_SELECT         2082
#define IDC_TMP_VAR_SELECT_TYPE         2085
#define IDC_TMP_SELECT_SCORM_LABEL      2086
#define IDC_TMP_SELECT_SCORM            2087
#define IDC_SCORM_CATALOGENTRY_GROUP    2088
#define IDC_CATALOG_NAME                2089
#define IDC_ENTRY_NAME                  2090
#define IDC_SCORM_LB_CATALOG            2092
#define IDC_SCORM_LB_ENTRY              2093
#define IDC_SCORM_LB_PURPOSE            2094
#define IDC_SCORM_CLASSIFICATION_SETTINGS_GROUP 2095
#define IDC_SCORM_PURPOSE               2096
#define IDC_SCORM_LB_CLASSIFICATION_DESCRIPTION 2097
#define IDC_CLASSIFICATION_DESCRIPTION  2098
#define IDC_SCORM_LB_CLASSIFICATION_KEYWORD 2099
#define IDC_CLASSIFICATION_KEYWORD      2100
#define IDC_SCORM_CLASSIFICATION_GROUP  2101
#define IDC_RENAME_PROFILE              2102
#define IDC_DELETE_PROFILE              2103
#define IDC_NEW_PROFILE                 2104
#define IDC_EDIT_PROFILE                2105
#define IDC_ACTIVATE_PROFILE            2106
#define IDC_DEACTIVATE_PROFILE          2107
#define IDC_IMPORT_PROFILE              2108
#define IDC_EXPORT_PROFILE              2110
#define IDS_PROFILE_MANAGER             2111
#define IDC_SCORM_DESC_SETTINGS_2000CHARS 2112
#define IDS_FLASH_STOPMARK_LOSS         2113
#define IDS_FLASH_STOPMARK_NUMBER       2114
#define IDS_FLASH_STOPMARK_TIME         2115
#define IDS_FLASH_PAGE                  2116
#define IDS_START_REPLAY_PAUSE          2117
#define IDS_SLIDE_FORWARD               2118
#define IDS_SLIDE_BACKWARDS             2119
#define IDC_FLASH_LOST_STOPMARKS_LIST   2120
#define IDS_JUMP_TO_BEGIN               2120
#define IDS_JUMP_TO_END                 2121
#define IDS_SOUND_ON_OFF                2122
#define IDS_ACTIVATED                   2123
#define IDS_NAME                        2124
#define IDC_ICON_WARNING                2125
#define IDS_TARGET_FORMAT               2125
#define IDC_TMP_VAR_IMAGE_ADJUST        2126
#define IDS_TESTING_QUESTION            2127
#define IDS_TESTING_ANSWER              2128
#define IDS_TESTING_POINTS              2129
#define IDS_TESTING_ACHIEVED_POINTS     2130
#define IDS_TESTING_SUM_OF_ALL_POINTS   2131
#define IDS_TESTING_ACCURACY            2132
#define IDS_TESTING_ATTEMPTS            2133
#define IDS_Q_CORRECT                   2134
#define IDC_TMP_VAR_WARNING_ICON        2134
#define IDC_LIST2                       2134
#define IDC_PROFILE_LIST                2134
#define IDS_Q_WRONG                     2135
#define IDS_Q_ALREADY                   2136
#define IDS_Q_ATTEMPTS                  2137
#define IDS_Q_TIMER                     2138
#define IDS_QQ_CORRECT                  2139
#define IDS_QQ_WRONG                    2140
#define IDS_QQ_ALREADY                  2141
#define IDS_TESTING_RESULT              2142
#define IDS_TESTING_PASSED              2143
#define IDS_TESTING_FAILED              2144
#define IDS_TESTING_MAXIMUM_POINTS      2145
#define IDS_TESTING_REQUIRED_POINTS     2146
#define IDS_TESTING_REQUIRED_PERCENTAGE 2147
#define IDS_TESTING_ACHIEVED_PERCENTAGE 2148
#define IDS_TESTING_CORRECT             2149
#define IDS_TESTING_WRONG               2150
#define IDS_EVAL_NOTE                   2151
#define IDS_STORAGE                     2152
#define IDC_EDIT_NAME                   2153
#define IDC_LABEL_NAME                  2154
#define IDD_PROFILE_SETNAME             2155
#define IDS_WARN_IMG_CONVERSION_FAILED  2156
#define IDS_DESC_IMG_CONVERSION_FAILED  2157

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2158
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         2137
#define _APS_NEXT_SYMED_VALUE           2000
#endif
#endif
