/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imc_lecturnity_util_NativeUtils */

#ifndef _Included_imc_lecturnity_util_NativeUtils
#define _Included_imc_lecturnity_util_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif
#undef imc_lecturnity_util_NativeUtils_FULL_VERSION
#define imc_lecturnity_util_NativeUtils_FULL_VERSION 0L
#undef imc_lecturnity_util_NativeUtils_EVALUATION_VERSION
#define imc_lecturnity_util_NativeUtils_EVALUATION_VERSION 1L
#undef imc_lecturnity_util_NativeUtils_UNIVERSITY_VERSION
#define imc_lecturnity_util_NativeUtils_UNIVERSITY_VERSION 2L
#undef imc_lecturnity_util_NativeUtils_UNIVERSITY_EVALUATION_VERSION
#define imc_lecturnity_util_NativeUtils_UNIVERSITY_EVALUATION_VERSION 3L
#undef imc_lecturnity_util_NativeUtils_VERSION_ERROR
#define imc_lecturnity_util_NativeUtils_VERSION_ERROR -1L
#undef imc_lecturnity_util_NativeUtils_SUCCESS
#define imc_lecturnity_util_NativeUtils_SUCCESS 0L
#undef imc_lecturnity_util_NativeUtils_NO_REDIST_PACKAGE
#define imc_lecturnity_util_NativeUtils_NO_REDIST_PACKAGE -21L
#undef imc_lecturnity_util_NativeUtils_SYSTEM_NEEDS_REBOOT
#define imc_lecturnity_util_NativeUtils_SYSTEM_NEEDS_REBOOT -22L
/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    getDllRevision
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_util_NativeUtils_getDllRevision
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    getEnvVariable
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_util_NativeUtils_getEnvVariable
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    getSpaceLeftOnDevice
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_imc_lecturnity_util_NativeUtils_getSpaceLeftOnDevice
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    startFile
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_imc_lecturnity_util_NativeUtils_startFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    isUserAdmin
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imc_lecturnity_util_NativeUtils_isUserAdmin
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    getInstallationDate
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_util_NativeUtils_getInstallationDate
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    getEvaluationPeriod
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_util_NativeUtils_getEvaluationPeriod
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    getVersionType
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_util_NativeUtils_getVersionType
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    getVersionString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_util_NativeUtils_getVersionString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    getVersionStringShort
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_util_NativeUtils_getVersionStringShort
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    getVersionStringShortShort
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_util_NativeUtils_getVersionStringShortShort
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    getVersionRevision
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_util_NativeUtils_getVersionRevision
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    getExpirationDate
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_util_NativeUtils_getExpirationDate
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    isProtectedDocument
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_imc_lecturnity_util_NativeUtils_isProtectedDocument
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    getLanguageCode
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_util_NativeUtils_getLanguageCode
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    getPlayerProperty
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_util_NativeUtils_getPlayerProperty
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    setPlayerProperty
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imc_lecturnity_util_NativeUtils_setPlayerProperty
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    getPublisherProperty
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_util_NativeUtils_getPublisherProperty
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    setPublisherProperty
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imc_lecturnity_util_NativeUtils_setPublisherProperty
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    getApplicationDataDirectory
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_util_NativeUtils_getApplicationDataDirectory
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    getRegistryValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_util_NativeUtils_getRegistryValue
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    getCurrentMicroseconds
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imc_lecturnity_util_NativeUtils_getCurrentMicroseconds
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    retrieveVideoInfo
 * Signature: (Ljava/lang/String;Limc/epresenter/filesdk/VideoClipInfo;)Z
 */
JNIEXPORT jboolean JNICALL Java_imc_lecturnity_util_NativeUtils_retrieveVideoInfo
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    retrieveFirstVideoFrame
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_imc_lecturnity_util_NativeUtils_retrieveFirstVideoFrame
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    installTwlcCodec
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_imc_lecturnity_util_NativeUtils_installTwlcCodec
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    deinstallTwlcCodec
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imc_lecturnity_util_NativeUtils_deinstallTwlcCodec
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    lecturnityUpdateCheck
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_util_NativeUtils_lecturnityUpdateCheck
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    lecturnityUpdateConfigure
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_util_NativeUtils_lecturnityUpdateConfigure
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    doInstallWmEncoderRedistribution
 * Signature: (Ljava/lang/String;ZZ)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_util_NativeUtils_doInstallWmEncoderRedistribution
  (JNIEnv *, jclass, jstring, jboolean, jboolean);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    doInstallWmFormatRedistribution
 * Signature: (Ljava/lang/String;ZZ)I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_util_NativeUtils_doInstallWmFormatRedistribution
  (JNIEnv *, jclass, jstring, jboolean, jboolean);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    systemNeedsReboot
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_imc_lecturnity_util_NativeUtils_systemNeedsReboot
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    getSystemCodepage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_imc_lecturnity_util_NativeUtils_getSystemCodepage
  (JNIEnv *, jclass);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    isFileLarger2GB
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_imc_lecturnity_util_NativeUtils_isFileLarger2GB
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    checkNeedsFinalization
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_imc_lecturnity_util_NativeUtils_checkNeedsFinalization
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    getFinalizedPathName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imc_lecturnity_util_NativeUtils_getFinalizedPathName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    sendDptMessage
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_imc_lecturnity_util_NativeUtils_sendDptMessage
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    sendPublishMessage
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_imc_lecturnity_util_NativeUtils_sendPublishMessage
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imc_lecturnity_util_NativeUtils
 * Method:    failWithLiveContextInstallation
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_imc_lecturnity_util_NativeUtils_failWithLiveContextInstallation
    (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
