# Makefile 29.10.01

TOPDIR = ../../..
LOCALDIR = imc/epresenter/filesdk

SUBDIRS = util audio
CLASSES = FileResources.class ArchivedFileResources.class SimpleFileResources.class \
          FileStruct.class Archiver.class XorInputStream.class XorOutputStream.class \
          FileFormatException.class ResourceNotFoundException.class \
	  Metadata.class ThumbnailData.class \
	  ConsistencyChecker.class PresentationData.class \
	  SearchEngine.class SearchResult.class SearchException.class \
	  SearchConstants.class VideoClipInfo.class Question.class Questionnaire.class \
	  Feedback.class StopMarkReader.class

include Makefile.inc
